### ISSUE TITLE
Bigger Bit Bags

### ISSUE THREAD

**Issue by Utildayael** [ChiselsAndBits/Chisels-and-Bits#104]
I know there is a setting for bit stack size so you can really just crank that up to something stupid but...

Would be nice to have "bigger" bit bags. Like the normal one as is but a "bigger" one that maybe needs an ender chest as the middle item in the recipe instead of a bit or something? Would have double the inventory. Just an idea. I run around a lot with a dozen bit bags and have to keep swapping them out based on what I'm working on. 

What would be super neat [and this is a HUGE reach and possibly not even a thing that could be done] would be a "AE" system for only bits with a wireless controller as the only access to it so you can "bulk store" bits in this special bits AE and use the wireless pad to access them and search. The pad would double as a "bit bag" for purposes of crafting items as it has access to all items in the "bit AE" system.

I'm mostly a builder so I go kind of nuts with chisel and bits. It's like microblocks on steroids. I love it. :)

Cheers!

**Comment by ghost** [comment]
Here's an idea for either Algo or whoever it is that makes ender storage: an ender bit bag. This would be pretty useful, and would allow you to somewhat implement the aforementioned AE for chisels and bits, without all the overhead. You could link the ender bit bag to either a regular ender chest or make a new ender bit chest if you wanted, so that the sizes of the inventories match up, then you'd be able to use AE or refined storage to automate the input and output of bits to and from the chest, and access them from your inventory. You could even connect this with the [Drawers & Bits Mod](https://mods.curse.com/mc-mods/minecraft/247712-drawers-bits) to automatically create bits! The more I think about this, the more I like it.
