### ISSUE TITLE
Update to 11.8, Lost All C&B Blocks

### ISSUE THREAD

**Issue by Utildayael** [ChiselsAndBits/Chisels-and-Bits#108]
Well this is painful.

Server updated C&B to newest version and every single C&B block on the server disappeared. Every. Single. One.

MC 1.10.2
chiselsandbits-11.8

**Comment by AlgorithmX2** [comment]
Did they have delete erroring entities enabled...? 11.9 fixed an issue caused by a missing class.

No one else I know of was able to even load their server worlds on 11.8. it simply crashed.

**Comment by Utildayael** [comment]
I'll check.

Interesting bit was that I had a few blocks [sadly not all] in a chest and they were ok. Just world-placed blocks poofed.

**Comment by Utildayael** [comment]
Not seeing that setting in your config.. is that a C&B config item or somewhere else?

**Comment by AlgorithmX2** [comment]
Its a forge setting ( Server Side )

**Comment by Utildayael** [comment]
Ah gotcha. I asked out server admin [RedLotus] to hop on the thread with that information.

**Comment by AlgorithmX2** [comment]
I checked my own forge.cfg, it should be B:removeErroringTileEntities

**Comment by Utildayael** [comment]
Roger. The fix I'm guessing, well fix sort of, is "update to 11.9" ...

May need to sooner than later. I tried to chisel a block and server crashed. Insta-crash on logon now when it starts to render. Sadly don't have access to server logs but alerted admin to it.

Since you said most people couldn't even load their world with 11.8 I'm not terribly concerned. :)

**Comment by AlgorithmX2** [comment]
Turns out I may have been incorrect in my assessment that the servers were unable to start, the two people I heard from noticed the errors on startup, and shutdown the server and either rolled back, or  immediately updated to 11.9

If the chunks the blocks are in didn't save then the tile-entities will probably load fine on update. Its unfortunate that this bug escaped into the wild.

I've hidden the problem versions on Curse Forge so no one else encounters the issue.

**Comment by Utildayael** [comment]
You can go ahead and close this one. We're going to upgrade to 11.9 to fix the issue. Thanks for taking down the problematic versions!
