### ISSUE TITLE
Storing large amounts of bits lags inventory screen.

### ISSUE THREAD

**Issue by BootyToast** [ChiselsAndBits/Chisels-and-Bits#116]
Oh man it took me forever to figure out which mods was causing this. I use Refined Storage so I'm not sure if this would be a problem with every mod that adds large scale item storing, but when the C&B blocks are displayed on screen the GUI will often freeze and microstutter.

I should mention that this doesn't happen in 11.7 and only in 11.9.

**Comment by AlgorithmX2** [comment]
I just filled a double chest and my entire inventory with bits, and I see no frame lag, micro-stuttering, or any sort of memory issues; In sort the game seems to be running fine while displaying 90 stacks of bits.

I'm not sure how many stacks your Refined Storage system is displaying, is it many more then that?

If possible please try to follow the directions [here](http://ae-mod.info/profiling/) to provide an NPS file recorded while the problem is happening. ( obviously post the file here and not the AE2 tracker however. )

**Comment by AlgorithmX2** [comment]
I also see no changes between 11.7 and 11.9 that would result in item rendering changing, most of those changes were for block rendering.

**Comment by BootyToast** [comment]
Hmm, I've no idea! Here's this file for you though. Hopefully I did everything correctly! 
https://www.dropbox.com/s/6zgmbgo2l8hvltp/cb3.nps?dl=0

**Comment by AlgorithmX2** [comment]
That worked wonderfully.

The issue doesn't appear related to Bits, but rather chiseled blocks.

It seems that refined storage is constantly re-sorting / filtering the list. This causes it to request the name of each item constantly, causing C&B to have to re-read the data from the item possibly hundreds of times each frame.

I'll see about improving the efficiency for this, but it also is somewhat the fault of the other mod for not caching that information, or only sorting once when the user selects the sort order, or filtering.

**Comment by AlgorithmX2** [comment]
Feel free to try https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/5/artifact/build/libs/chiselsandbits-11.0.5.jar

I added some code on my end to hopefully prevent this sort of issue with C&B in the future with other mods since I can't guarantee that someone else won't do the same thing.

Either way the improvement for refined storage would be a good thing in the long run.

**Comment by BootyToast** [comment]
I've tested a bit and this alone has fixed the issue. Thanks a bunch!
