### ISSUE TITLE
Please add the mod to Modrinth

### ISSUE THREAD

**Issue by Alter73** [ChiselsAndBits/Chisels-and-Bits#1189]
Hi! I just make quite a lot of modpacks (not just me) in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if such a popular mod as Chisels & Bits was also in Modrinth, otherwise I have to download it separately and check for updates, but this is very inconvenient when creating modpacks.

**Comment by marchermans** [comment]
No, after internal discussions, contacting other modders, and trying to figure out if the platform has a future, the answer is simply no.

Whether you like it or not, we do this in our free time. The little bit of income we get from CF compensates this. To upload, maintain and manage a modrinth posting, that time spend on that posting needs to be compensated somehow. And in reality it turns out that modrinth is at the moment simply not a viable platform, it pays out several (3+) orders of magnitude less to its content creators then CF, and as far as we all could see has no future.

As such I respectfully decline to upload to modrinth.

**Comment by Alter73** [comment]
Thank you for the reply! I didn’t know that mods were developed for money, I never received money from my mods. Uploading a mod to Modrinth does not prohibit you from still uploading the mod to CF, I don't see a problem. Plus many mods have become available on both CF and Modrinth. Okay, got it.

**Comment by marchermans** [comment]
It is not about the money. 
It is complicated to explain. I do this because i enjoy it. Because i enjoy the fun people have with c and b. 

But nothing in life, not even time, is free. I spend several hours every week working on this. Doing moderating work in the community, helping people with issues, fixing bugs. Those are hours I could spend working and earning money, so I could buy a house, food, fuel for my car or pay hospital bills. 

I don't actually earn a lot of money from c and b but it is enough that instead of spending one  hour every few weeks on this, I can spend three or four every week. It is not even remotely close to my salary in my day job, but it allows me to at least spend time on this project and not feel guilty one way or another. 

I don't ask for direct payments or very often for  patreon support, but the incoming from the ads that you see on curseforge at least allows me to take my wife out for dinner once a month or so, as a way of making it up to her that I spend time on this project rather then spending time with her. Stuff like that.

If I upload to modrinth I would need to spend time figuring out the platform, how to moderate and provide support on it. Set up the infrastructure to maintain new releases there, all of this costs time. Now if the ad income from that site was high enough, I would do it in a heartbeat to help you guys out. But I asked several other modders which have mods of the same size what they earn and if they would distribute on modrinth again with the knowledge that they have today. Not one said yes. The platform is not mature enough. It is as simple as that.

I am open to discuss this further. 

Greets,

Orion

**Comment by Alter73** [comment]
Yes, I notice different excuses for everyone not to upload the mod to Modrinth. I understand everything, it just seems like all experienced modders know something about Modrinth. I was chatting on Github at Twilight Forest and one of the developers said that they didn't like monetization methods and the way they do business, and a day later this topic was deleted. If you know something about it, then if it's not a secret, then please say something about it, otherwise I completely don't understand what's going on. I contacted some other modders, but they only say that this platform has no future and something about monetization, but why did so many modders decide to switch to Modrinth?
