### ISSUE TITLE
MCMP - Invalid Collision Results

### ISSUE THREAD

**Issue by AlgorithmX2** [ChiselsAndBits/Chisels-and-Bits#132]
When placing bits inside of an MCMP block it sometimes results in random, and unusual results.

https://cloud.githubusercontent.com/assets/4707702/17910870/0d8bd0e6-698b-11e6-8de3-4e85470d717f.png

The issue doesn't seem to be in C&B as it only becomes an issue when testing non-C&B parts for collision, however I hasn't been able to track it down beyond that.

**Comment by Utildayael** [comment]
Run into similar issues with other mods and building C&B stuff around them. I thought it was a collision issue on the mod's end and filed a bug report with that mod. For example, Refined Storage supports MCMP but their cables break if you accidently put a C&B into the cables "space" in the block.

Refined Storage bug:
https://github.com/raoulvdberge/refinedstorage/issues/255

FWIW, I tried to repro your Mekanism example and was not able to. It seems to full respect the collision space, does not destroy/pop the Mek cables, and generally works great. Never had invisible blocks or any of that mess and breaking the block works as expected. The stone ones I made had a bit more hardness to them than expected but otherwise broke fine and place fine.

MCMP 1.21

**Comment by AlgorithmX2** [comment]
Well I've never had C&B break a cable in any of my tests, My example was specifically about the unusual erratic random placement of bits as seen in that screen shot.

If there is something about RefinedStorage's cables breaking that is probobly completely unrelated, and sounds like some kind of MCMP - Refined-storage interaction.

**Comment by Utildayael** [comment]
Not surprising. That mod has... Uh. A few bugs. "Few"

Have never seen what OP reported with Mek tho and I do a _lot_ of multis in diff configurations to hide my pipes and wires. Will keep an eye out tho and report if I can reproduce.
