### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Susjin** [ChiselsAndBits/Chisels-and-Bits#138]
After updating C&B to version 12.2, i'm getting an crash when starting the game

crash log:
http://pastebin.com/v2XsvV6J

**Comment by AlgorithmX2** [comment]
Hmm seems like the optimizations for the calculations are calling methods in other mods before they are ready.

**Comment by AlgorithmX2** [comment]
I'll have to pull 12.2 until I can resolve it. For now revert to 12.1

**Comment by Susjin** [comment]
Ok =D

**Comment by AlgorithmX2** [comment]
Mind giving https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/lastSuccessfulBuild/artifact/build/libs/chiselsandbits-12.0.21.jar a shot? It should have the fix for the crash in it, I'll need to do some more testing on my own, but if you can confirm that its working with your instance that would be a good first step.
