### ISSUE TITLE
Block Hardness sometimes changes with rotation, inordinately hard blocks when liquids are used

### ISSUE THREAD

**Issue by Yowesephth** [ChiselsAndBits/Chisels-and-Bits#14]
When a block is composed of half liquid and half solid, it being rotated can sometimes change it's hardness. 

Looking at the ground, I place 1 plane of quartz, and 1 plane of lava on top of it. It broke at the speed of quartz. After being rotated so that the quartz plane is facing upwards, the block seems to take on the liquids hardness, causing it to take an exceptionally long time to mine. (similar to mining obsidian with an unenchanted diamond pick)

This might only be with quartz and lava. I've tried it with some other blocks and they seem to keep the hardness value they have, though that value isn't always a solid or liquid hardness value (yellow stained clay and water had a long break time, reliably. Emerald block and lava had emerald's break time reliably)

**Comment by AlgorithmX2** [comment]
Hmmm interesting, I imagine its because there are equal quantities of two materials, the block tends to act like the most common material, since a lot of behaviors are not variable, for the most part it works ok.

Say if theirs 100 stone, and 100 water, whichever the systems finds first will probably 'win' on the hardness front, I might need to add something to tweak the reported values of hardness for fluids then, since that is probably extreme.

It would probably be more accurate to calculate a new hardness that weighs the contents... but that will use more memory to store it cause calculating that every tick while mining would be too slow.. Not sure that's worth it.
