### ISSUE TITLE
Weird Graphical Bug issue when having Chisel and Bits installed

### ISSUE THREAD

**Issue by DatrixTHLK** [ChiselsAndBits/Chisels-and-Bits#140]
When I had your mod installed the game chunks didn't load immediately, Graphical glitching issues were occuring with the textures in the game. When looking up information on your mod in the FEI subset menu The game flashed black and then back to normal several times until it was closed out. I will send my FML Log at a later time today since I am working currently. Just thought I'd let you know about it. referencing issue [#32](https://github.com/elix-x/Forever-Enough-Items/issues/32) of Elix-x github issues page.

**Comment by AlgorithmX2** [comment]
If I'm reading your report correctly, your reporting 3 issues.

When C&B is installed your chunks aren't loading?
When C&B is installed your textures are breaking?
When C&B is installed your FEI menus are flashing.

I'm uncertain as to the first two, I don't know why C&B would break chunk loading or the texture atlas, it doesn't do anything low level to either of these functions, especially if C&B blocks are not present.

The last one sounds like a simple GL state conflict.

**Comment by AlgorithmX2** [comment]
I tried to test for the submenu issue however having FEI installed seems to simply crash both my dev instance and my non-dev instance. and I don't have time to try and figure that out right now.

If someone else wants to look into the submenu issue, feel free.

**Comment by DatrixTHLK** [comment]
I'm sure about issue #2 and #3 but I'm still unsure as to #1 seeing as my fml log is very spammy with other mods I have installed giving out warnings/errors about them.

Sounds good, I'll let Elix-x know about it if he doesn't already.

**Comment by AlgorithmX2** [comment]
I don't really know what to say about about the first two, unless you can find some way for me to reproduce the issue, I've never had any texture related issues with C&B, nor have I heard about it from anyone else.

Like I said before, I'm not doing anything with textures other then using the normal item textures, so unless your seeing issues because your atlas has too many sprites or something, it just seems extremely odd that C&B which only has like 7-8 normal items would corrupt your textures. Same with chunks, I don't mess with chunk loading at all, not even with events, C&B mostly only deals with rendering geometry.

it might be a bit different if you were using C&B extensively so it was creating lots of geometry to upload to your graphic card maybe causing you to run out of graphics memory or something, but from the sounds of it your just experiencing it having it installed, in which case there would be nothing uploaded geometry wise.

To me it just sounds like C&B might be causing an issue that exists else where to suddenly show up, maybe because its causing the mods to change load order, or something. I've honestly got no ideas about why, though.

**Comment by DatrixTHLK** [comment]
What you say makes sense. I'm very confused as well...Well I'll test out the mod loadout I have and see which mod is really interfering in some way with yours. I'll let you know about it in a few days. If nothing different shows up then I'm at a loss. If the issue doesn't occur then I'll know. It is also possible that I used a previous version of your mod just before you updated as well.

**Comment by DatrixTHLK** [comment]
When I downloaded your mod tonight and looked it up on the subset menu in FEI it did crash to desktop. You were correct, I used a previous version of your mod just before you updated. 12.3.

**Comment by AlgorithmX2** [comment]
If your reporting a crash I'll need the crash log. a crash in a FEI menu sounds like an FEI problem however.

**Comment by DatrixTHLK** [comment]
I think it is more of an FEI problem since looking at it in FEI subset menu is where it crashed me. Oh well, thanks for helping out anyways.
