### ISSUE TITLE
crash with refined storage 1.10.2

### ISSUE THREAD

**Issue by ilordnightmarei** [ChiselsAndBits/Chisels-and-Bits#149]
http://pastebin.com/jFqAD1Zs
serching for  books made this

forge version 2095

**Comment by AlgorithmX2** [comment]
Any idea what the chiseled block is in the system? its crashing trying to test a block for culling ( something in the chiseled block )

Its strange that you have bits for a block that crash when using the vanilla culling test, I would think that couldn't happen. since it obviously was rendering in the world before it ended up in a chiseled block.. then you put it in the chiseled block, broke it then put it in to the storage system.

Only then it crashed, I'm quite puzzled by that.

**Comment by ilordnightmarei** [comment]
same here but typling bo crashed it so soothing with bo also the server updated recently

**Comment by AlgorithmX2** [comment]
https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/lastSuccessfulBuild/artifact/build/libs/chiselsandbits-12.0.29.jar give that a go and let me know if that solves the issue.

**Comment by ilordnightmarei** [comment]
its on a server tho XD  ill send this to whatthedrunk and well see what happens

**Comment by AlgorithmX2** [comment]
No Response, Closing.
