### ISSUE TITLE
Underwater C&B

### ISSUE THREAD

**Issue by NanoCE** [ChiselsAndBits/Chisels-and-Bits#152]
If you submerge a bit creation under a liquid like water, it still takes up a full block and moves the water out of the way. What if a block is submerged it would render the liquid on the side that there is the liquid. This feature would allow for detailed underwater bases that don't stick out. I know this would be a bit of a task to do but It would be worth it.

**Comment by AlgorithmX2** [comment]
I'm fairly sure that this would actually require modding water itself to be aware of C&B blocks and to cull its faces based on C&B Blocks.

The issue is also present with things like transparent glass, since the blocks don't treat the bits as the same type of block, you can see the face between chiseled stained glass, and stained glass.

The same issue applies to water, water and chiseled water are diffrent, thus the faces beetween them will always render. Reguardless of if the C&B block contains water, or wants to "fake the existence of water".

I don't think its feasible.

**Comment by NanoCE** [comment]
I know the author of carpenters blocks was able to do it. Could you not bare bones it and have it so when a C&B block is placed it checks for any water around it and would then make itself have the property to "connect" to the water block next to it how other water blocks do. It would be far from perfect but it wouldn't require modifying the vanilla water and would still allow under liquid detail.

**Comment by AlgorithmX2** [comment]
I'm not sure if its possible to modify which faces water culls without modifying water, I admit I just don't know, usually culling is determined by the block itself, and not the block next to it.

Did the carpenters blocks version not have any visual artifacts? I didn't see anything about face culling in its logic, but it does seem to use fluids as a means of determining if its blocks are opaque or not.

That sounds like it would potentially cause artifacts however. Things in post 1.7 are different, its possible that how culling has worked has changed some.

In the end I guess I'll just have to look into trying it and see how it works, and if its possible with or without forge patches.

**Comment by NanoCE** [comment]
That is the most I can ask for. I know 1.7.10 is quite different graphically than 1.8+. This mod would of not existed otherwise. Thankyou.

**Comment by Kasuyakema** [comment]
I ran into the same Problem, how about two kinds of chiseled water bits? one with redered, flowing sides and one without it? One could use the second kind  to fill in the air in submerged chiseled blocks to make them blend in with the rest of the water

**Comment by AlgorithmX2** [comment]
@Kasuyakema I'm not sure that makes much sense, plus bits are tied to states, those states are tied to blocks "one does not simply create states" since i'm just referring to other people states, not my own.

**Comment by nico-oas** [comment]
Are there any updates on this topic? I too would really prefer the water to not look like [this](https://i.imgur.com/wqlwBE8.png) when combined with chiseled water.
I am also fine with you modding water itself, but since this could make the mod interfere with other mods more easily I would recommend that you make it an optional thing that you have to activate either in-game or download separately.
Beaches could look incredible with this mod! 😎

**Comment by maxashen** [comment]
Maybe this forum post can help: http://www.minecraftforge.net/forum/topic/42816-solved-render-partially-transparent-block/

And here's his repo: https://github.com/JayAvery/jjmod

![2017-04-09_18 44 44](https://cloud.githubusercontent.com/assets/11188862/24841524/c2292242-1d54-11e7-963b-5c0f65761ac0.png)

**Comment by NanoCE** [comment]
^This^ is what I meant of what carpenters blocks does. Thanks @Max-Shen0

**Comment by AlgorithmX2** [comment]
Even if its possible to take advantage of face sorting in this manor, I'm uncertain if the end result will work as well as you you think it does.

For instance, what happens when you have a chiseled block, under water between several other chiseled blocks? And no water? Suddenly there is no water? So then those blocks have to scan further to figure out if they are submerged, What if your chiseled blocks intended to be an "Inner wall" Suddenly water "leaks" though the wall, and becomes visible inside the structure.

This sort of solution works fine in the case of a block like his plant, but becomes much more complicated, and thus much slower to try and work out in a much more complicated scenario like C&B.

C&B would need to analyze the water, and determine which bits would "flow" water into themselves. scan other C&B blocks for "flow" indefinitely to be perfect ( which is impossible because no computer has infinite resources.  Then make corrections for the fluid high to match up with normal water, and all the while deal with partial water flows, and everything else.

I honestly think that this will only end badly, in more ways then one.

**Comment by maxashen** [comment]
When a C&B Block is placed/created on a fluid source block, maybe replace the fluid source block with the C&B block/TE and set a new field "submerged"=[fluid]. Then when you render, add the extra fluid model on the translucent layer - basically you just render a translucent cube with the fluid texture. When you pick up (mine) a C&B block just gut the submerged field.

I don't think you should handle "flooding" of C&B TEs at any point other than block placement, because as you said it would involve more handling, and if they want it submerged they can always pick up the C&B block, put a fluid source block in the empty space, and place the C&B block back down. If the player wants only part of the block submerged (for example a 1 bit wall holding the water out) they will have to use water bits.

As far as chiseled water not blending with normal water, from what I gather you need to use a second model on the translucent layer for those bits.

**Comment by NanoCE** [comment]
So instead of checking for flooding, this would make it so opaque C&Bs(water) would render transparent on the sides, so it is easy to blend into the water block nearby. Flood handling wouldn't really be needed in this case. I'm not sure.
