### ISSUE TITLE
Crash report: chisel bag & moving bits = crash

### ISSUE THREAD

**Issue by Kaisoul** [ChiselsAndBits/Chisels-and-Bits#159]
I made an iron chisel & a bit bag gathered a few stacks of granite bits when to move the bits into the bag then crash.....

[crash-2016-11-01_18.15.30-server.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/565287/crash-2016-11-01_18.15.30-server.txt)

**Comment by Kaisoul** [comment]
sorry about just dropping the crash log on here like this atm my pastbin login is being emo...

**Comment by AlgorithmX2** [comment]
Kinda weird that xreliquary is listening for stuff in the bit bag, but whatever I can test for it.

---

If you want to give the fix a try, https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/36/artifact/build/libs/chiselsandbits-12.0.36.jar

Other wise I'll push out an official build in a little bit.

**Comment by P3pp3rF1y** [comment]
@AlgorithmX2 the reason that I am listening is so that I can actually display void tear contents when these are in inventories (because I need to update item handler caps on client side for that). 
Yes it doesn't make sense to listen to bit bag as void tear will never go in there and I could add a blacklist of container possibly, but in general I don't know what kind of containers players can put void tear in and thus need to listen to all. 
Honestly I would rather like to see caps have a way to sync with the packets so that I wouldn't have to do this listener magic at all.

**Comment by AlgorithmX2** [comment]
Yeah, that would probably make more sense. Well its not like it was hard to fix, I guess its just one of those things that people will have to patch if they are sending custom packets to listeners. ( if they are not already testing for the player )

**Comment by AEnterprise** [comment]
@P3pp3rF1y could this be what you are looking for? https://github.com/MinecraftForge/MinecraftForge/pull/3342
