### ISSUE TITLE
Automation of Chiseling bits and creating blocks

### ISSUE THREAD

**Issue by Cathillach** [ChiselsAndBits/Chisels-and-Bits#169]
My friends and I are trying to create a dwarven kingdom in Hermitpack at the moment. We wish to use chisel and bits to create custom blocks for the floors and pillars and walls. If we try and do this manually then we will end up still creating it a few years down the track.

Is there any way to chisel a block using a machine and then to have another machine with a pattern that creates the desired blocks for use in an RFTools builder, for example.

Cheers

**Comment by AlgorithmX2** [comment]
To my knowledge it should be possible to a build with chiseled blocks with a builder, blocks can presently only be manufactured with patterns and bags, and only chiseled at all with chisels.

This is of course by design, trying to keep the content in the mod directed towards vanilla, I've always had ideas regarding more industrialized approaches, however I believe they belong as an add-on of sorts to C&B.
