### ISSUE TITLE
Customize Bit Size

### ISSUE THREAD

**Issue by GeneWeaver** [ChiselsAndBits/Chisels-and-Bits#171]
a config option to  increase minimum size of bits,  i would love to set the medium size block as the smallest size bit.
again thanks for the mod!!!

**Comment by AlgorithmX2** [comment]
I'm not sure this makes sense, if you did this you would never be able to go smaller, where as grid-snapped modes allow you to get similar functionality without removing lower level detail entirely.

If you changed your LOD after using the mod you blocks would basically corrupt.

**Comment by prado93** [comment]
what he is saying is that could have a config option to change the bit grid

**Comment by AlgorithmX2** [comment]
@prado93 I realize that.

@GeneWeaver wants to make the bits larger, this is the opposite of you, who want them to be smaller. As my response explains, I'm not sure making the bits larger makes much sense when you can already us grid snapped modes.

And if you adjust the grid it means you cannot change it again, so after a month of playing with the mod on 8x mode, if you suddenly decide that you wanted to use 16x again, you can't, because it would corrupt all your blocks or something.

**Comment by maxashen** [comment]
You could just make it a client-side option to limit the chisel/place mode sizes, something like a check box for each size in the forge mod config GUI. Server-side the blocks would be stored the same way.

**Comment by AlgorithmX2** [comment]
There already client side options for this.
