### ISSUE TITLE
Crash caused by a clash between multipart and refined storage 

### ISSUE THREAD

**Issue by TheMprs** [ChiselsAndBits/Chisels-and-Bits#177]
so i played in my singlplayer modded world and then it suddenly crashed, it crashes every 15mins or so
i posted about this in the refined storage thread and they sent me here, they said this:
"After talking with ama for a very brief period of 5 minutes, we've both come to the conclusion that some other mod that utilises the MCMP API didn't update yet to utilise new API features.

A big suspect is Chisel&Bits. But Algo is fixing that apperently. So I can close this."
(link: https://github.com/raoulvdberge/refinedstorage/issues/632)

here's the pastebin for the crash: http://pastebin.com/3KQdJM8V

**Comment by AlgorithmX2** [comment]
Feel free to try https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/lastSuccessfulBuild/artifact/build/libs/chiselsandbits-12.0.52.jar

This includes the API Changes mentioned, if it does indeed fix I'll probobly have to release a new build, if not I believe you'll be back to square one.

**Comment by TheMprs** [comment]
thank you sm :)

**Comment by TheMprs** [comment]
this just happened:
http://pastebin.com/XSUzGDHf

**Comment by AlgorithmX2** [comment]
So that doesn't seem like it fixed anything.

**Comment by AlgorithmX2** [comment]
This means that perhaps C&B may in fact not be the cause of the issue, back up and try removing mods to verify the source of the issue? Based on the crash it could be any MCMP mod in use, its hard to say which, if you find a way to reduce it down to a minimal set say one MCMP mod and MCMP then perhapes it would be possible to further test and find the cause.

However just saying "its C&B because it didn't update the API" at this point is no longer true, since you have tested the version with the updated API.

**Comment by TheMprs** [comment]
I can't remove mods and do so, as it crashes every about half an hour currently, and removing each mod will just take too much time that I don't have :/

**Comment by AlgorithmX2** [comment]
I see, I suppose that we are at a dead end then, it was a long shot that it was C&B as is, and I don't have much time to chase down bugs like this either.

**Comment by AEnterprise** [comment]
this crash looks like a network issue to me, i suspect some mod is accessing the world from the networking thread instead of the main thread causing the non-threadsafe map to crash

**Comment by TheMprs** [comment]
So do you have any guesses as to which mod might cause this to happen

**Comment by AEnterprise** [comment]
looking at the logs i would suspect eighter refined storage or if there are other multipart blocks on your cables that mod

you have any idea of why they suspected C&B or even that a mod is still using an outdated api?

**Comment by AlgorithmX2** [comment]
@TheMprs do you have a list of MCMP Parts your using? this won't include redefined storage, since it uses BlockCoverable, but other things you place inside of it would, such as C&B, or covers or other things?

I was talking with @amadornes and @raoulvdberge and we're lacking for ideas at the moment, so that information might help. Knowing what your actually using vs trying to guess from the mod list.

**Comment by AEnterprise** [comment]
can you try without optifine? the crash seems like a threading issue but the crash is when it's trying to render a block, optifine might be doing some threading causing issues

**Comment by TheMprs** [comment]
It happened when I didn't use optifine too, I got worried it'll be that so I tried

**Comment by AEnterprise** [comment]
alright, other then one of the mods accessing from the wrong thread i'm out of idea's

@amadornes would a sanity check in MCMP be an option to prevent access from a different thread (or log a stacktrace)?

**Comment by amadornes** [comment]
The thing is... this should not be anymore in MCMP 1.3.0, so I don't know why it happens here. I didn't plan on supporting the 1.10 version now that I'm rewriting everything for 1.11 and I have no clue how big of a performance hit it would mean to have that thread check... but I could do it if it's *REALLY* needed.

**Comment by AEnterprise** [comment]
would a debug version be an option? with that thread check but just for him to use and see if anything pops

**Comment by TheMprs** [comment]
Sure I'll do it, if I may, but I could only test starting from Sunday I'm out of time :/
