### ISSUE TITLE
Forge MultiPart to C&B Convertor

### ISSUE THREAD

**Issue by endermatrix** [ChiselsAndBits/Chisels-and-Bits#183]
Forge MultiPart to C&B Convertor
-royal pain to hand make/replace multiparts in a 300x300 chunk city [killx20 midgar for the win]
-1.7.10 to 1.10.2 forge multipart to C&B would be lovely
-non in-game app with block type ID selector
-converting missing blocks to defualt miissing block replacer [basicly a marker that says hey this is not here,
         maybe phantom block that a copy or delete tool would replace with the block pasted into?]
-Convert whole map Option
-Convert Chunk Option [In-game block, when placed in chunk starts the convert on redstone signel?
         so that id conflicts wont spawn convertor randomly in world and its creative mode only? or a OP
                     accessable Gui?]

**Comment by AlgorithmX2** [comment]
This isn't something I will be doing.

An add on could potentially detect, and convert FMP Blocks via the API, or another might could also convert to MCMP or something instead, not sure what would be best.

Either way I don't have the time to do this, or manage any sort of options, or tools to convert things without the game. Which the different options would requires, since FMP isn't a mod anymore, you can't install it at the same time, and thus by failing to load the data would just go away. 

You either would have to convert the data as its loaded with ID-Remapping, or use an external tool to convert the entire world at once.

Maybe there is a modder out there that wants to convert his 1.7 world to 1.10 or something and would feel motivated into doing something like this.
