### ISSUE TITLE
Pattern Library

### ISSUE THREAD

**Issue by monkeybug34** [ChiselsAndBits/Chisels-and-Bits#194]
It would be wonderful if there was a library that let you save your patterns to a client-side file and load them up in any other world or server. it would enable players to design their blocks in a creative world, and then all they need to do is collect the materials to make them on the server/SSP world they are playing on.

**Comment by Rory-Lambert** [comment]
On a similar vein, perhaps a catalogue item would be useful for storing your designs; load your patterns in to the catalogue and browse through previews of the block. Once you have found the design you want, place your bit bag in the catalogue on that page to create the block, similar to how generating blocks from a positive design works at present. This would be super useful for keeping all your designs in one place, especially since they are non-stackable!

**Comment by Arudarin** [comment]
Have we gotten anywhere with this?
