### ISSUE TITLE
Crash on entering the world

### ISSUE THREAD

**Issue by Dijkstra1-zz** [ChiselsAndBits/Chisels-and-Bits#206]
Twice i have crashed with this bug, u lucky i read the crash report past the first section or forestry would have got it when it is an issue with c&b

here's the crash report see what u make of it

**Comment by AlgorithmX2** [comment]
There doesn't appear to be any report.

**Comment by Dijkstra1-zz** [comment]
ops sorry that what happens when u r up till 5am here it is 
https://gist.github.com/Dijkstra1/4fc0b8278a1fe195d6cc0e3e80312521
and make it 3 times now

**Comment by AlgorithmX2** [comment]
To confirm you have chiseled Forestry Green houses?

**Comment by Dijkstra1-zz** [comment]
not me it is a public server who's knows what people r doing

**Comment by Dijkstra1-zz** [comment]
i found the block in question it does not seem have green in it

**Comment by AlgorithmX2** [comment]
You can see the block? That is rather puzzling, I wonder how it can render the block when it crashes making the model.

**Comment by Dijkstra1-zz** [comment]
Do not ask me it is your mod, there a share function right would it help if i sharded the block
https://gist.github.com/Dijkstra1/50db2d98b99d3c8d4e76c097f4a17e3d, looking at that still looks like there is no greenhouse in it, however we do have greenhouse up a tree near by (don't ask)

**Comment by AlgorithmX2** [comment]
I'm honestly not sure how you can even see the block, If it contains an invalid id, then it should crash all the time, not just some of the time.

The fact that your only getting this error randomly indicates something... But I have no idea what.

**Comment by AEnterprise** [comment]
this could be a block id desync, if one of the coremods is messing with the registry (and maybe breaking it) the client could think it's another block then actually is on the server

**Comment by AlgorithmX2** [comment]
If a mod/coremod is doing something like this, then yes, it absolutely could be the cause. Such would be very difficult to track down, especially since its random already,

**Comment by Homeboi999** [comment]
My world Crashes on open, but i only have Chisels and bits, and Extra bit manipulation.
I've Re-made my world a lot, and am only playing singleplayer.
What do i do?

//Version 1.11.2
//Crash Report (latest)   |
                                      V
[crash-2017-09-02_09.33.56-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/1272235/crash-2017-09-02_09.33.56-client.txt)

**Comment by AlgorithmX2** [comment]
I'm afraid I'm not sure what is the issue, perhaps try a different version of forge? The stack-trace you've provided is entirely vanilla. And is crashing regarding the sky color, something that neither mod would modify.

**Comment by Kijuma** [comment]
Hello, regarding the singleplayer-crash...maybe I can give some usefull input here.
I have experienced something similar today, after I tried to copy some chiseled blocks, my client had a forced shutdown.

Only thing I can think of after cooling my head down a bit would have to be some kind of 
memory-overflow or not-enough-memory-available event. 
Regarding this theory, is it possible that the MC-client counts every surface-area that isn't covered by another micro-block seperately which in return would increase the overall memory required by java with the crash to follow?

On a side-note, I was - and am still - able to salvage my savegame by using mcedit 
to wipe the player inventory since it seems like those copied fully chiseled blocks are what's causing the crash in the first place, maybe trying to copy-paste chiseled blocks that are too complicated in structure and/or adjacent to complicated blocks bring the client down?

Here's my crash-report if that helps
[crash-2018-01-04_18.50.04-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/1604246/crash-2018-01-04_18.50.04-client.txt)

**Comment by AlgorithmX2** [comment]
@Kijuma 
The issue was that Conquest Reforged crashed while C&B was requesting a display name for a rotated pillar block of some kind. I'm not sure how you can chisel a rotated pillar?

I'd ping the developer, but I have don't know if they have a github account and their mod appears to be closed source. Nothing to do with surfaces, or memory. Maybe try asking them to check on it?
