### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by MrAmericanMike** [ChiselsAndBits/Chisels-and-Bits#223]
Is there any way to stop this spam on the console?

http://pastebin.com/T9uNHNXT

I would think that this does it, but no: 

troubleshooting {
    B:enableAPITestingItem=false
    B:logTileErrors=false
}

**Comment by AlgorithmX2** [comment]
There's no way to disable those messages, because they are important, they are printed when C&B preventings java from crashing because of class loading failures.

If you really want to get rid of those, you could install one probe. 

McJty's mods use the one probe API, and when C&B tries to check if those blocks are chisable and one probe isn't installed, java fails to load the class, and crashes. I'm currently catching those crashes, and displaying that message, usually its a sign that something should be fixed.

Goes quite a way back as well, https://github.com/McJty/RFTools/issues/608

**Comment by MrAmericanMike** [comment]
Thanks a lot ;)
Yes I'm trying to clean a bit the console in general :D
Thanks for the answer.
