### ISSUE TITLE
Exportable object libraries

### ISSUE THREAD

**Issue by lendrick** [ChiselsAndBits/Chisels-and-Bits#227]
I was thinking it would be nice to be able to create libraries of our own objects and then export them to a folder, which could then be added to other modpacks or downloaded on their own.  It would be nice to be able to set up custom recipes for those objects.  In this way, people could make furniture and object "mods" without having to mess around in external modelers or writing java code (instead releasing them as object libraries for C&B).

**Comment by AlgorithmX2** [comment]
Creating blueprints for objects that can be saved and exported it one thing ( https://github.com/AlgorithmX2/Chisels-and-Bits/issues/212 ). I fully intend to get back to this at some point.

However I don't plan on doing anything like a way to craft them that way requires preventing editing of those blocks because your crafting them with other resources, which in turn would allow resource conversion, and other weird results.

If someone wanted this they would need to write a addon.
