### ISSUE TITLE
Liquid starlight bits don't emit light

### ISSUE THREAD

**Issue by Geird** [ChiselsAndBits/Chisels-and-Bits#245]
As the title says, bits made from the Astral sorcery mods liquid starlight do not emit light. Changing block percentage to 0 does not affect this, nor does adding more bits, at least not until it's a full block.
![2017-03-12_16 51 22](https://cloud.githubusercontent.com/assets/23565524/23835875/49bbe788-0745-11e7-9039-b7ad46c2f7c0.png)
![2017-03-12_16 51 26](https://cloud.githubusercontent.com/assets/23565524/23835874/49bbaeee-0745-11e7-87d9-5890a0489d4b.png)

**Comment by AlgorithmX2** [comment]
Never mind on the mod.. I see you put that in there, I missed it on the first read.

Lava bits worked last time I checked, so its possible that the mod is doing something differently that makes it more difficult to detect the lighting, or error prone, in which case threes not much that can be done.

**Comment by AlgorithmX2** [comment]
I just looked at the block in the mod's source ( https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/block/fluid/FluidBlockLiquidStarlight.java )

There doesn't appear to be any sort of "Light Level" attached to it, however it adds night vision to the player, is that what your expecting? If so C&B doesn't do that.

Also maybe your talking about the particles? Also C&B Doesn't do this, C&B treats all fluid bits as "Water Bits" useful for decoration and the like, but trying to emulate complicated logic like collision based effects or display tick effects can lead to crashes or other situations, so C&B doesn't do these. 

I prefer to get the best compatibility I can, without risking crashes, which is why I support what I do, there are potential ways to support these effects, but since that involves putting those mods into situations they were not designed for, I prefer to not do those things, as it can cause unexpected results,, bugs and crashes.

**Comment by Geird** [comment]
![2017-03-12_17 56 20](https://cloud.githubusercontent.com/assets/23565524/23836394/a75d426c-074d-11e7-9ec0-c18ac6bd281b.png)
I wasn't expecting night vision, since I'd be converting the liquid into a another mods thing. It definitely emits light though, maybe whatever value does that is stored somewhere else/phrased oddly?
Also, I forgot about 1.11 being around, and this is 1.10.

**Comment by AlgorithmX2** [comment]
Seems that the fluid has a luminosity set... might be related, Alright just making sure its what I normally support before I get more in depth.

**Comment by AlgorithmX2** [comment]
Alright, I've worked out the issue, fluid blocks used the more complicated method for reporting their light value, but I should be able to use that method, so it will be fixed in future versions.
