### ISSUE TITLE
Best configuration for online usage?

### ISSUE THREAD

**Issue by Fioz** [ChiselsAndBits/Chisels-and-Bits#246]
Hello, I'm trying to understand what is the best configuration possible to have a smooth experience (fps wise) with C&B in a multiplayer server, I've tried looking into the options but i don't understand what's the best combination.  
This is because i'm trying to convince my admins to allow this mod into our server but they are scared players will over use it and make every potato lag (we may have large cities of 200-300plot+ with 50-100 players each and i've tried doing 30/40 medium building made of simple microblocks and i lag quite a bit) or that a single troll will be able to make a city lag with little effort (copying and pasting a single harsh chiseled block).

I'm also thinking if it's possible to ban certain things for example banning the copy/paste/mirror/etc papers so that players can only make small structures and that making entire building out of bits is not doable easily or maybe restrict the bits to only a larger size (1/8 of a block so that you can make vertical slab etc). I've seen the options in the configuration but i don't know if it's a good idea or if it's going to work online

sorry to bother you Algorithm but can you help me and light a way for me to follow? I'd love to have this mod on the server, it's the perfect mod for MC in my opinion!

**Comment by AlgorithmX2** [comment]
I can make a few notes,

One is that complex blocks use a separate renderer ( unless your using optifine - which breaks that behavior )

That renderer has additional options, such as render distance, and you can control how many faces is required to trip that renderer, so different players can control which renderer to use, and what the render distance is for those more complicated blocks, allowing them to fine tune the mods rendering for their machine.

I've done my best to make the mod as performance friendly as possible, and to give those values a reasonable default, but any given graphics card can only process so much data before it slows, potato's or not.

In my opinion banning patterns is the worst thing you can do, since it is a major part of what enables the mod to be fun, forcing everyone to do things each time, is just monotonous.

I can't really compare C&B with other micro-block, since its ability to hide faces, use models and cache calculations are entirely different from a traditional micro-block mod pre-1.8.

With that said I think you'll just have to use your best judgement or do some testing, build some things, copy/paste them build something that you think is reasonable for testing then have some of those players with potato's try it.

I don't know how well you'll be able to combat trolls, anyone can build anything that can cause problems, MC just is that sort of environment, building a base out of hoppers, or creating tons of redstone loops can cause conformance issues, at least you can relax with the fact that C&B shouldn't bother your server at least.

**Comment by Fioz** [comment]
thanks for your imput! I have one last question before entering a test phase in which i'l try to convince my admins of it, if we decide to try the mod and people use it and then we decide to remove it, what would happen to the map of the server? Could it get destroyed/damaged in some way(other than removing the chiseled blocks/items)? this could  be a decisive thing

Still thanks and great job with the mod, even if the admins won't accept it (shame on them) i'm alredy using it on my SP world and I'm having loads of fun! I think you did a fine job with optimizing it!

**Comment by AlgorithmX2** [comment]
If you uninstall the mod, the blocks and the items will all be removed, obviously if you remove a mod you should back up just in case something goes wrong, but if there was an issue with removal it might be related to another mod, since forge's default behavior is to just convert any blocks into air, and remove any items as they are loaded.

C&B doesn't do anything like changing formats or change any default minecraft behavior, so there should be no issues.
