### ISSUE TITLE
Bits from non-vanilla blocks don't import correctly when using structure blocks

### ISSUE THREAD

**Issue by omega025** [ChiselsAndBits/Chisels-and-Bits#249]
When using C&B 12.12 in MC 1.10.2, using structure blocks to import a structure from another saved world, bits from Immersive Engineering blocks will usually appear as Flat Colored Blocks bits. Similarly, sometimes bits from Flat Colored Blocks will simply not appear at all when importing a structure that contains them from another saved world.

**Comment by AlgorithmX2** [comment]
C&B doesn't support cross world structure blocks, this is because of the compressed format that it uses. And it requires some verity of forge patch to enable support for this.

In the mean time you might try Recurrent Complex, it should have support for C&B.

**Comment by maxashen** [comment]
How bad does it get if you always use registry IDs in TileEntityBlockChiseled.writeNBT? I don't see Forge adding a special method like te.exportNBT().

**Comment by AlgorithmX2** [comment]
Its a petty sizable inflation for the cross world format for some blocks, in the range of over 300% in some cases, just because simple blocks compress very well right now, but if I were to use string id's in all cases it would case significant inflation in size.

I'm currently of the mind set that its not worth it for this.
