### ISSUE TITLE
Cutout Layers of different materials bit-cull each other.

### ISSUE THREAD

**Issue by VsnGamer** [ChiselsAndBits/Chisels-and-Bits#25]
Placing Leaves(maybe any transparent block) on chiseled blocks makes this render bug.
Reproduced in Minecraft forge 12.16.0.1797 [1.9] with Chisels and Bits[9.5] no other mods, no Optifine, only forge and C&B.
Thanks.

![2016-03-22_11 16 09](https://cloud.githubusercontent.com/assets/18006201/13950688/5c83147e-f024-11e5-9baf-0895ad50317c.png)

**Comment by damew** [comment]
It seam that you "fix it".  I thing i know how you "fix it" and why that was happening most likely he was in Fancy block rendering of leave as he most likely did not try others transparent blocks or you made it with fancy block rendering in mind.  The  "fix" I was that now the bit render in Fast.  If that is the case not to me as I have to play my modded world in Fast but maybe those who use it in Fancy and like how the leave look might not like it.

PS: mostly speculation.

**Comment by AlgorithmX2** [comment]
This has to do with how C&B does bit surface erasure. Which normally works fine, since all glasses for instance render as "Transparent" any transparent surfaces will block other transparent surfaces.

It breaks some with the cutout layer, which is used for Normal glass, Leaves, and Grass oddly enough.

I'll probably just need to make any separate cutout material behave separately.

**Comment by AlgorithmX2** [comment]
Fixed by https://github.com/AlgorithmX2/Chisels-and-Bits/commit/3404c831f2ac0640b607e7928b16a0de69edbfb0 !
