### ISSUE TITLE
This mod doesn’t support Biomes o’ Plenty’s blocks

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#255]
I can’t chisel them.

**Comment by AlgorithmX2** [comment]
Does your log contain any details? Perhaps an error from C&B saying something is wrong?

Are the blocks you are attempting to chisel normal blocks?

**Comment by ghost** [comment]
I can’t see anything in the log. It makes sense not to get an error, because when I try to chisel the block, I just break it like I would if I were to hit it with my hand.

I tried to chisel a silty dirt block from BoP.

**Comment by ghost** [comment]
@AlgorithmX2 This does not look good.

![2017-04-04_07 03 01](https://cloud.githubusercontent.com/assets/25916106/24642062/cdaafd92-1904-11e7-94c5-2c3e27daa01b.png)

I just checked Chisels & Bits’ config file, and none of Biomes o’ Plenty’s blocks are listed under “enabled blocks.”

**Comment by AlgorithmX2** [comment]
What doesn't look good? It looks like some dirt and some stone?

**Comment by ghost** [comment]
On the left is silty dirt from BoP, and on the right is vanilla dirt. I wanted to cover up some Refined Storage cables, but I can’t, since I can’t use silty dirt with Chisels & Bits, so I had to use vanilla dirt.

**Comment by AlgorithmX2** [comment]
Please wait patiently so I can find some time to research the issue, pestering me with passive aggressive comments about how my mod is making your base less appealing doesn't help anyone.

**Comment by PapiDimmi** [comment]
I’m explaining the issue so that you can understand what the bug is. You asked me for info, and I gave you it. I had no idea that you were “researching the issue.”

**Comment by ghost** [comment]
I’m explaining the issue so that you can understand what the bug is. You asked me for info, and I gave you it. I had no idea that you were “researching the issue.”

**Comment by AlgorithmX2** [comment]
I'm not referring to the details you provided, those are helpful, I'm referring specifically to "@AlgorithmX2 This does not look good."

Which did nothing to improve the situation, and only made me ask what I was looking at, only to get a response that "I wanted to cover up some Refined Storage cables, but I can’t, since I can’t use silty dirt with Chisels & Bits, so I had to use vanilla dirt."

And I didn't say you were aggressive, I said those comments were "Passive Aggressive" 

In any-case once I have some time to look into the problem I'll post back with what I find.

**Comment by ghost** [comment]
I posted that comment mainly to say that I can’t find any Biomes o’ Plenty blocks listed in Chisels & Bits’ config file. I decided to add a screenshot that shows you what the bug results in in my comment. It’s not a super important screenshot, but the comment in itself is probably pretty important, and the screenshot certainly doesn’t hurt.

I just said “This does not look good” to show you what this bug looks like… nothing more, nothing special. I apologize if I seemed aggressive, but I certainly didn’t intend to.

**Comment by AlgorithmX2** [comment]
You seem to reacting rather strongly to a minor complaint on my part, I'll try to explain.

I'm not trying to indicate that your being abusive, or mean. I was simply stating that your comment, was passive aggressive.

You also seem to have the wrong idea about what I mean by "Passive Aggressive" I didn't mean you were outright demanding or insulting, or even aggressive.

I was simply stating that your comment sounds like complaining, or whining that the issue is not fixed. As I said above, this may not be your intention, but from my point of view, it certainly sounded like it, which prompted me to comment on it.

I did not intend for this to escalate in this fashion, I'm just asking for patience so that the issue can be researched.

**Comment by PapiDimmi** [comment]
This is literally the most pointless and embarrassing argument I have ever had with a human being, and that’s probably entirely my fault.

**Comment by AlgorithmX2** [comment]
Ok, so the issue was that BOP Dirt Ticks. This is normally blacklisted because of potential issues, most of them having to do with balance.

I have however added a new setting, "Black List Ticking Blocks" in the gui, or "blacklistTickingBlocks" in the config file.

That allows you to change this behavior to false, and get ticking blocks to be supported. Feel free to try the test builds below.

1.10.2 Link: https://www.dropbox.com/s/gtqsx2s57jrg5g8/chiselsandbits-12.0.jar?dl=1
1.11.2 Link: https://www.dropbox.com/s/1a62adxtwjfcgtw/chiselsandbits-13.0.jar?dl=1

**Comment by ghost** [comment]
Thank you. I really appreciate it.
****
Can you explain what dirt ticks mean? What kind of ”balance” are you talking about? Are there any side effects to disabling blacklistTickingBlocks?

**Comment by AlgorithmX2** [comment]
The block will randomly "tick" or process updates to pull grass from surrounding blocks into it self. This is more or less how normal grass works, but in its case, its the reverse.

In some cases ticking blocks might be used for certain mechanics, for instance wheat grows. What the blocks do is up to them, but C&B by default ignores such blocks because there might be implications to that material and its "ticking"

If your not worried about that, then you don't need to really worry about it. Its a choice between "Certain mechanics" and "Decoration"

**Comment by ghost** [comment]
Thanks, but I’m not sure I fully understand yet: does disabling blacklistTickingBlocks make it so that crops can’t grow on tilled Biomes o’ Plenty dirt and grass blocks?

(By the way, I apologize for my discourtesy earlier.)

**Comment by AlgorithmX2** [comment]
No, C&B doesn't effect any other blocks, its just a matter of which can be chiseled, and which cannot.

**Comment by ghost** [comment]
Oh, I understand now. Thanks.

**Comment by TomJTaylor67** [comment]
Is there anyway to do this with Biomes o Plenty mud blocks?
