### ISSUE TITLE
Quickly draining fluid tanks?

### ISSUE THREAD

**Issue by KyuuGryphon** [ChiselsAndBits/Chisels-and-Bits#266]
Sorry if this has already been brought up or is already implemented, I've looked but can't find anything on it.

Is there a way to drain a fluid tank all at once, as opposed to one layer at a time? It'd be a nice addition, as opposed to having to hold down the right mouse button for a while when you're working with a lot of fluid bits.

**Comment by AlgorithmX2** [comment]
You can use hoppers and other mods to pull out the bits as well, if you intend on working with a lot of bits that might be helpful.

As for a faster way to pull out more that doesn't involve that, not at the moment.

**Comment by karikusa** [comment]
Hello hello!
This mod is so wonderful!
However, regarding the fluid tank, it is the same impression as KyuuGryphon.
Once removed, it can not be changed to other liquid until it is completely drawn out,
I need to pull it out anyway.
However, since it takes some time to pull out,
How wonderful it would be if you pulled out in bulk!
I am looking forward to the future development!
