### ISSUE TITLE
Angled bits

### ISSUE THREAD

**Issue by Beardlessbrady** [ChiselsAndBits/Chisels-and-Bits#276]
Not sure how easy or hard it would be, but it would be amazing if bits could have their angle rotated. For clarification if building a line diagonally you could turn the bits so they are one connected face and not zig-zagging corners.

**Comment by AlgorithmX2** [comment]
I honestly don't know that that would be that great... it would complicate rendering significantly, add a significant amount of data per block. And for the most part still be incapable of creating simple soaps correctly, because the lines will always be slightly off center.

Also it would mean that culling hidden faces between slanted and non-slanted would be neigh impossible.

**Comment by Beardlessbrady** [comment]
Hmm, was just a thought. I had no idea how complicated it would be
