### ISSUE TITLE
Combining chisels in anvil 

### ISSUE THREAD

**Issue by hanakocz** [ChiselsAndBits/Chisels-and-Bits#283]
I had two chisels with enchants, I combined them in anvil, enchants were combined as expected, but durability stayed same for the first chisel, even though those should combine (I was combining nearly destroyed with full one). Probably the behaviour cannot count with such a high durability or custom durability is used and mechanics not adjusted.

For any bug reports please provide the following,

* MC Version: 1.10.2
* C&B Version: 12.12
* Do You have Optifine: no, also not relevant :)

**Comment by AlgorithmX2** [comment]
This appears to be an issue with the code in the anvil, for some reason when combining two damaged items, it checks the metadata. This is silly, since metadata doesn't necessarily have anything to do with damage, so probably a forge/vanilla idiosyncrasy.

But using materials appears to work fine, and merging two stacks in the crafting table like wise appears to work fine.

**Comment by AlgorithmX2** [comment]
I submitted a forge patch for this, weather or not its accepted for 1.12 it will probably be fixed in 1.13 when metadata goes away.
