### ISSUE TITLE
Exploit in rotation with wrench

### ISSUE THREAD

**Issue by GWSheridan** [ChiselsAndBits/Chisels-and-Bits#327]
When rotating a block next to cactus thats on top of snad or vanilla sand you can multiple cactus very quickly with a block update has to be a chisel an bits block in the middle of the cactus like the gif 
https://gyazo.com/7e097927bee79a7013bec994778ade4d

* MC Version: 1.10.2
* C&B Version: 12.16
* Do You have Optifine: No

**Comment by Dushess** [comment]
Link is broken.

**Comment by GWSheridan** [comment]
investigated this further not just this mod does it its more to do with MC an block updates does it with any wrench that can rotate any block. Example AE2 with a chest

**Comment by AlgorithmX2** [comment]
I just tried to reproduce this in 1.12, if I rotate a block on the same level of the sand nothing happens. If I try to put any bits next to a cactus they immediately pop into items.

Perhaps you have another mod installed that allows cactus's to be next to bits? and that is some how causing an issue? or perhaps its an older vanilla bug which has been fixed?

**Comment by GWSheridan** [comment]
bit block needs to be one lower same level as sand an rotate it with wrench

**Comment by AlgorithmX2** [comment]
Please note that I've already tried that, "if I rotate a block on the same level of the sand nothing happens"

Have you tried this with only C&B installed? You have indicated that other block updates are causing the same problem, which either indicates that the problem is a vanilla issue which has been fixed in a more recent version ( 1.11 or 1.12 ), or its caused by another mod.

In either case I can't really do anything about it , unless I've misunderstood what you've said?
