### ISSUE TITLE
Chisel and bit and binnie mod

### ISSUE THREAD

**Issue by saphsara** [ChiselsAndBits/Chisels-and-Bits#328]
Hi, is there a way i can add to chisel and bit config file for the binnie mod. I would like to be able to chisel and bit their blocks. 

For any bug reports please provide the following,

* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by saphsara** [comment]
Minecraft 1.12.2

**Comment by AlgorithmX2** [comment]
From what I can tell The woods and such in Extra Trees are "BlockDesign" which extend "BlockMetadata" 

Which is https://github.com/ForestryMC/Binnie/blob/3fc36f8e37dba601588610a6b675a670953f5aee/core/src/main/java/binnie/core/block/BlockMetadata.java#L83

This unfortunately blacks lists the block, since they are storing more then a simple state per block. C&B cannot support a tile entity in its current configuration.

I'm not sure why their woods use tile entities, but it might be legacy code, or perhapes just a way to avoid using extra states. Not much I can do however based on that.

**Comment by saphsara** [comment]
Ok thank you for looking into it
