### ISSUE TITLE
Make C&B models applyable to weapons

### ISSUE THREAD

**Issue by Popgirl12** [ChiselsAndBits/Chisels-and-Bits#341]
I had an idea a while back for chisel and bit where you could create custom tools/weapon models using the mod so that roleplay modpacks could have custom items from chisel and bits.

**Comment by AlgorithmX2** [comment]
I know that @Phylogeny 's Extra Bit Manipulation lets you create custom armors however, so if your interested in that I'd recommend checking that out.

Not sure about weapons or tools, I think there is a major draw back to that since you can't just put in a pick Axe and "skin it" so if you have a fancy tinkers tool, or "uber death slayer axe 2000", you would have to trade that in for a "diamond sword with a fancy skin" which doesn't even cover things like modded tools.

**Comment by Phylogeny** [comment]
The ability to render custom chiseled block model sets in place of any specified item, whenever that item is held, is a feature is planned for EBM. Here is a detailed explanation of this and other planed features: https://minecraft.curseforge.com/projects/extra-bit-manipulation#c21

I even made a bit of progress on implementing it, then life got in the way, so I haven't touched EBM in nearly 2 months. I hope to get back into it soon, but even then, as I explain in the link above, this will require alot of refactoring and time to implement.

All that said, I make no promises as to when even just this one feature will be finished.

**Comment by AlgorithmX2** [comment]
I certainly understand how that goes, I've made so little progress on C&B lately, though I've been trying to make a push to finish up blueprints this last week. I started it back in Mar 10, 2016

**Comment by BlueYoshi68** [comment]
so is there an ETA on when this is gunna be a thing?
