### ISSUE TITLE
Compatibility with DavincisVessels?

### ISSUE THREAD

**Issue by alphapapa** [ChiselsAndBits/Chisels-and-Bits#353]
Hi there,

Is there any chance of Chisels-and-Bits being compatible with DavincisVessels someday?  I'm guessing the work would need to be done on the side of DavincisVessels rather than Chisels-and-Bits, but I don't know that for certain, so I thought I'd ask here as well.  

I tried to make a ship that had one chiseled block, and when I clicked Assemble Ship, it said it assembled OK, but when I tried to mount the ship, the clients on the server crashed.  The server didn't crash.  (Since I doubt there's anything to do on this end, I'm not going to post the debug log here, but I can provide it.)

I can't offer any assistance with writing Java, but I'd be glad to assist with any testing.  The ships we could make with these mods together would be amazing.  :)

Thanks.

**Comment by AlgorithmX2** [comment]
Without knowing what the crash is I can't say anything, I would imagine its up to DavincisVessels to resolve it however, since the issue likely has something to do with the way the mod works. Its probably some sort of "fake world" or something like that.

If I had more information or the mod author wanted to discuss something about my mod that is causing an Issue I would certainly be willing to help.

**Comment by alphapapa** [comment]
Ok, I'll provide a log as soon as I get a chance, just in case there's something that can be done on this end.  I appreciate your help and your generosity with your time.  This is an amazing project!

**Comment by alphapapa** [comment]
Ok, here is a log from when it crashed when I clicked "Mount Ship" in Davincis.

[crash-2017-12-17_00.19.42-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/1569607/crash-2017-12-17_00.19.42-client.txt)

There is a closed issue on the Davinci tracker (https://github.com/elytra/DavincisVessels/issues/175), but it isn't clear from what's there if there is any chance of fixing the crash.  I added a comment asking about it, and hopefully the author will have time to get back to us sometime.  I know we're all busy with real life things.  :)

Please let me know if I can do anything else to help.

**Comment by AlgorithmX2** [comment]
The crash itself was during rendering, and it seems when it was rendering the ship itself, unfortunately that doesn't really point towards any specific cause, at least not that I could look into.

**Comment by alphapapa** [comment]
Thanks for taking a look.  Maybe @darkevilmac will have some ideas.  Let me know what I can do to help!

**Comment by darkevilmac** [comment]
Alright, it was because C&B gets a chunk from given coordinates to get its tile for rendering. I've made a tiny FakeChunk impl that I'll extend.

Now that they render there's a whole other issue that I can't guarantee I'll ever end up working on. That would be rotation.

https://cf-b2.streamablevideo.com/video/mp4/9091o.mp4?token=1513845940-nfDFJF64tOjqOB52AYW%2FReNhugmG%2BaTu6JYQHXzh8yQ%3D

**Comment by alphapapa** [comment]
@darkevilmac 

> Alright, it was because C&B gets a chunk from given coordinates to get its tile for rendering. I've made a tiny FakeChunk impl that I'll extend.

Wow, that's great!

> Now that they render there's a whole other issue that I can't guarantee I'll ever end up working on. That would be rotation.

Does that mean that ships must be assembled facing the same direction or the C&B blocks may be turned?  An unfortunate limitation, but not game-breaking.  :)  I understand there are no promises, we all do this in our free time.  Thank you very much for your work on this!

**Comment by AlgorithmX2** [comment]
I'm not entirely sure what you mean by rotation, but C&B tile entities do support the vanilla mirror and rotate methods. That may or may not be relevant however.
