### ISSUE TITLE
[1.12.2] Unable to pass stairs made with Chisels and Bits

### ISSUE THREAD

**Issue by Draskh** [ChiselsAndBits/Chisels-and-Bits#360]
I made stairs with Chisels and Bits but you can't walk on top. It does not matter which block is used, modded or vanilla. 
![2018-01-04_13 20 47](https://user-images.githubusercontent.com/26455012/34563575-60833694-f153-11e7-865a-2041fb32b64e.png)
You stuck in this position and can't go forward.
You must remove a block thick layer to pass but then they are smaller than normal stairs.
![2018-01-04_13 24 09](https://user-images.githubusercontent.com/26455012/34563636-a02048d2-f153-11e7-9a9f-c25a9e3d1b30.png)

Forge: 1.12.2 - 14.23.1.2566
Optifine 1.12.2 C7
CB: 14.11
(Chisel: MC1.12-0.1.1.24, because block is used, but also appears with Obsidian)

**Comment by VladimirMangos** [comment]
As I test need remove only one line bits instead plane

**Comment by AlgorithmX2** [comment]
By "Can't walk on top" you do mean that you can't "step up" rather then "you fall though"?

If so I think your in for a mod scavenger hunt, this bug is usually caused by a mod setting player stepHeight to 0.5 instead of 0.6 this was quite common back in 1.8 when that value was changed, maybe your using some less common mods that haven't updated it yet.

You'll want to set up a new instance, and try recreating the issue with fewer and few mods. A good starting point is mods that have things like "boots of stepping" or other items that let you up up and down full blocks without jumping.

**Comment by VladimirMangos** [comment]
Yes, way just blocked. Impossible go up by stairs without jumping.

**Comment by AlgorithmX2** [comment]
Yeah, its almost certainly the same old issue, You'll need to track down which mod is at fault and report the issue to them. Make sure to start by removing mods that you know have some sort of step assist.

The issue is that player.stepHeight should be 0.6F not 0.5F you can pass that long when you report the issue, or point them back here.

**Comment by Draskh** [comment]
Yeah, it seems that the step height is set incorrect. Is there any mod know for causing that issue? I loaded a lots of mods and don't know how I should identify the right one.

**Comment by AlgorithmX2** [comment]
Fortunately every time we have identified one before it was fixed.

I recommend pulling out half the mods, testing, to see if it works.
If its still broken, pull half of what remains, if it works add half. 

Basically repeat until you find the right mod.

**Comment by Draskh** [comment]
I will check this on the weekend and will reply then.

**Comment by Draskh** [comment]
I updated my modpack with new versions of some mods and removed a few. It seems that the issue solved itself.

**Comment by ghost** [comment]
Can you post a list of those mods here, I'm having the same issue and am rather lazy :p

**Comment by Draskh** [comment]
Sorry, but I do not remember them all. 

> Fortunately every time we have identified one before it was fixed.

> I recommend pulling out half the mods, testing, to see if it works.
> If its still broken, pull half of what remains, if it works add half.

> Basically repeat until you find the right mod.
