### ISSUE TITLE
Slabs not working properly with higher full blocks 

### ISSUE THREAD

**Issue by asperan** [ChiselsAndBits/Chisels-and-Bits#368]
Specs:
* MC Version: 1.12
* C&B Version: 14.11 & 14.12
* Do You have Optifine: No
* MCMP Version: 2.4.1

Slabs made of bits don't allow to step on the next block, if the latter is higher by half a block, like in this picture.
![picture](https://user-images.githubusercontent.com/14941985/35672179-f922737e-073d-11e8-9d66-228f4d62b23d.png)

I tried hollow and filled slabs, and I built them using both bits and the diamond saw.
I'm sure that above me there isn't anything and vanilla slabs are working.

I hope this isn't a big problem, your mod is one of my favorite ones for building, keep the awesome work!

**Comment by AlgorithmX2** [comment]
You most likely have another mod installed that's changing the player's stepHeight to 0.5 instead of 0.6, I would recommend making sure that all your other mods are up-to-date, if that fails to fix the issues you can try to isolate which mod it is that is making the change and report the issue to the mod developer.
