### ISSUE TITLE
[suggestion] config option for purely decorative water

### ISSUE THREAD

**Issue by stohun01** [ChiselsAndBits/Chisels-and-Bits#374]
I'm working on a modpack that prevents buckets placing water sources. Using water bits is a cheaty way around this. I suggest adding an option to prevent water source blocks being created when the block is 100% water bits and instead be a full block of decorative "water" that isn't able to irrigate farmland.

**Comment by AlgorithmX2** [comment]
Possibly, a second option might be to disable the Bit tank in your mod pack. Thought I suppose that limits creative freedom with the mod.

**Comment by stohun01** [comment]
I considered that, but for some reason disabling the tank causes a crash on startup. I just retested it with only forge and CB installed. loaded it up the first time, it worked fine. closed the game and changed the config so only the tank was disabled. loaded it back up and it crashes.

Minecraft: 1.12.2
Forge: 14.23.2.2623
CB: 14.14

**Comment by AlgorithmX2** [comment]
Yeah, that's definitely gonna be fixed.

**Comment by AlgorithmX2** [comment]
More or less,

"revertible states" {
    B:"minecraft%3Awater?level=0"=false
}

https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/122/artifact/build/libs/chiselsandbits-14.0.122.jar is a build server build with the feature if you want to test it out.

Other wise I'll probably release a new build in a few days.

**Comment by stohun01** [comment]
No crashing issues with the tank anymore, thanks. Normal water (flowing or still) next to a CB water block culls the side faces though.
![2018-02-28_14 41 55](https://user-images.githubusercontent.com/23627406/36770495-3d2ddef6-1c96-11e8-8fe9-cd5ddb1b3104.png)

**Comment by AlgorithmX2** [comment]
I'm honestly not sure there is a good solution for this. The water model is usual and doesn't fit to the pixel grid, and flows at a slant in some cases. C&B is using water default behavior, in that water next to water never renders a face.

![image](https://user-images.githubusercontent.com/2846930/36825020-e76b8696-1cca-11e8-8a05-85cd9b37eed2.png)

Is the best I've been able to come up with yet, basically if the water is flowing it renders the face, but since liquids don't fill the full block space a "full water block" still results in a gap.
