### ISSUE TITLE
Crashes with JEI

### ISSUE THREAD

**Issue by davqvist** [ChiselsAndBits/Chisels-and-Bits#386]
* MC Version: 1.12.2
* C&B Version: 14.16
* Do You have Optifine: Some yes, some no

I just link to you this issue: https://github.com/davqvist/Exoria/issues/173
It appears certain items appearing in JEI will crash to C&B. I will report back if I have more information. It seems that it has also something to do with Misty World maybe, but maybe you know what is going on and can help.

**Comment by AlgorithmX2** [comment]
Looking it it looks like ru.liahim.mist.init.BlockColoring is being called for "Air" I imagine that the mod is miss-registering its color handler for air, since that makes little sense, probably an order of operations issue where it gets registered before the item they intended to register or something else.

**Comment by AlgorithmX2** [comment]
I've gone ahead and patched this anyway since its probably something that will come up again.
