### ISSUE TITLE
Protection problem for Chisel&Bits events.

### ISSUE THREAD

**Issue by TeKGameR950** [ChiselsAndBits/Chisels-and-Bits#388]
I run a spongeforge server, i tried all protection plugins but there is some problems with your mod.

This issue is divided in 2 parts:

1.- If you try to chisel a block inside a protected region (GP, RedProtect, UniverseGuars,SafeGuard, FoxGuard, etc), you will get the drop but the block won't be modified.
**First: So we can dupe items with that. But i don't care**
Solution i think: Check if the block really got destroyed and if the event wasnt canceled

2.- If the block inside a protected region IS ALREADY chiseled, you will be able to modify it and you will also get the drop.
**I CARE!! ^^ Cause players can destroy the city 👎 **
Solution i think: Same as the first solution, cause for already chiseled blocks it seems like it ignore the block event

**If you don't want to install sponge, try with the default minecraft spawn protection i'm sure it do the same glitches**

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: Latest
* Do You have Optifine: Yes (Not related)

Thanks for reading.
Have a good day.

**Comment by AlgorithmX2** [comment]
Testing Vanilla spawn protection yields no changes on the server for either case.

Testing on a non-chisled block results in the block resetting to the previously non-chilsed status.

Testing on a chiseld block looks like it works, however when I re-log in the block has been unchanged.

This has to do with how spawn protection works, which in vanilla is very iffy, but since it works from the standpoint of preventing damage I saw no reason to peruse it further.

If this is different from sponge forge, It seems like it would be an issue with sponge forge? I didn't get any duplicated items either, so that seems strange.

**Comment by TeKGameR950** [comment]
Or how can i be sure that players in survival mode **CAN'T INTERACT** with bits?

Cause i only use chisels&bits for the city as its a rp server and players will never be authorized to use them.

Do an option exist? or a way to do that? 

Thanks.

**Comment by AlgorithmX2** [comment]
I think it makes more sense to find out why the protection mods are not working, or what the issue is with sponge forge.

But you could use a mod like mine-tweaker to remove the crafting recipe for chisels, or play in adventure mode instead. Depending on which works better.

Are positive that the modifications aren't client side only? and that they are actually modifying the world?

**Comment by TeKGameR950** [comment]
You should still fix the issue where the client can modify it clientside :)

Thanks. :)

**Comment by AlgorithmX2** [comment]
The problem is that doing so requires preventing the client from doing anything until the server approves of it. This means that it adds a full round trip length of latency before things can update. This isn't how MC Does things, it just lets you do whatever, and it probably will fix it later.

Its not always the case however, as when you try to place a block it just removes the block, but the block is missing form your inventory until MC bothers to re-sync it.

Hence why I'm not too keen on making that change. Its possible to possibly fix it another way, but for instance sending a "Did that work?" packet or forcing the server to send back every block that fails modification. But That sort of thing will tend to just use more bandwidth for cases that are quite likely more common.

**Comment by TeKGameR950** [comment]
Sponge fixed is part but there is another issue that is caused by your mod.

As you can see here.
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/390
