### ISSUE TITLE
[Request] Add gamemode checking for the entire mod use.

### ISSUE THREAD

**Issue by TeKGameR950** [ChiselsAndBits/Chisels-and-Bits#391]
Hi, i think it could be really cool if you could add a config option like

**canUseModInCreative=true**
**canUseModInSurvival=false**
**canUseModInHardcore=false**

to configure is the selected gamemode is able too break/places blocks.

Thats a really small request but should really be cool.

**Comment by AlgorithmX2** [comment]
This just dosn't seem like it makes sense in the context of the mod. Creative lets you break all blocks, and to my knowledge C&B can't prevent that. While C&B could prevent people in survival from breaking blocks inside of survival mode this seems like it would far more appropriate as a permissions mod, which is already another issue.

I can't see this being useful for almost any reason if that issue is resolved.

Also what is hardcore?

**Comment by TeKGameR950** [comment]
**Adventure** not hardcore sorry :/ 

I was thinking of that cause i really need to fix protection issue really quickly so thats why.

**Comment by AlgorithmX2** [comment]
Its far easier for me to fix the issue which has already been identified and found then by implementing new pile of arbitrary config values.

Besides I think adventure mode is specifically for preventing you from breaking most types of blocks. So that should already prevent you from breaking blocks. At least that is my understanding of the mode...

Regardless this just seems like trying to duck-tape permissions into the mod, which I don't think should be a thing.
