### ISSUE TITLE
Crash when opening inventory (ConcurrentModificationException)

### ISSUE THREAD

**Issue by brisingraerowing** [ChiselsAndBits/Chisels-and-Bits#403]
For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.18
* Do You have Optifine: No

[Crash Log](https://gist.github.com/BrisingrAerowing/563aa6a534b912223bc33b9dd3e371ec)

Loaded a world and tried to open my inventory.

**Comment by AlgorithmX2** [comment]
I don't think that this is caused by C&B, something is messing with the creative tab list in multiple threads, it just so happened that C&B was in the main thread and was busy updating the list when after something else did something.

That doesn't really help track down the cause, but since C&B isn't using threads here its really the only explanation I have.

**Comment by brisingraerowing** [comment]
It didn't repeat when I reloaded the world, so that's good. I'll see what I can figure out (if anything).
