### ISSUE TITLE
client crashes

### ISSUE THREAD

**Issue by 1xdarknessx1** [ChiselsAndBits/Chisels-and-Bits#41]
here's the crash report, the crashes were duplicable and only crashed the individual clients and not the server as a whole. the sever is running several mods and was wondering if this was a compatibility issue or something else altogether. 
[crash-2016-04-14_10.37.11-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/219839/crash-2016-04-14_10.37.11-client.txt)

**Comment by AlgorithmX2** [comment]
The stack-trace it self doesn't indicate any specific mod, unless you have steps to reproduce the issue It could be any of the mods on that list.

-- Updated --
The issue seems to be a missing texture for a block that the player is standing in, but that should require that the block your standing in return true for isFullCube, C&B doesn't do this.

Also I'm pretty sure that C&B reports a texture in all cases, even if the block is bad It returns the missing texture sprite.

**Comment by 1xdarknessx1** [comment]
thanks
