### ISSUE TITLE
Chiseled fluid transition with real fluid

### ISSUE THREAD

**Issue by Sewef** [ChiselsAndBits/Chisels-and-Bits#415]
* MC Version: 1.12.2
* C&B Version: 14.17
* Do You have Optifine: Yes (HD_U_E1)

Hello!
I was messing around with Chiseled Fluid (using Water) and I have an aesthetic issue : 

![2018-08-08_16 29 06](https://user-images.githubusercontent.com/27089398/43843884-cfd67a7c-9b28-11e8-81cf-a93a052f1adb.png)

My chiseled blocks are filled with Chiseled Water, but the regular water applies its outer texture and makes underwater bits contraptions pretty weird.
I don't know if it's easy to fix, maybe check the Water block code to see how its texture works?

**Comment by AlgorithmX2** [comment]
Unfortunately there is not a lot I can do about this issue either, since Water and C&B are two separate states, Vanilla water won't cull its faces, and C&B Won't cull its faces either.

I've experiments with culling C&B faces next to water, but it can cause other issues, such as gaps between the top of the water block and where water actually begins, because water has a strange arbitrary height.

There is also no way for me to change how water renders in a reasonable manor to make it cull faces next to C&B, since water is one solid face, and C&B is comprised of up to 256 smaller 'virtual' faces. Its just generally better to not mix real water and C&B"s water were possible.

Its not ideal but unless I high-jack the entire renderer and replace it with some sort of C&B variant that does special culling on water, and other transparent blocks like glass this will always exist.

Thats far to invasive for my taste, plus it would make the normal game's simple rendering logic into something far more complicated, which would make every block require more complex render logic, I would also have to change the water heights, and remove the angles to do it fully.

**Comment by Sewef** [comment]
Well, waiting 1.13 for underwater things is a better idea, so XD
I don't know how game rendering works, so I'm just guessing :>
