### ISSUE TITLE
Optifine compat : colormap for water

### ISSUE THREAD

**Issue by Sewef** [ChiselsAndBits/Chisels-and-Bits#416]
* MC Version: 1.12.2
* C&B Version: 14.17
* Do You have Optifine: Yes (HD_U_E1)

Surprise, I'm back!
Maybe you don't want to support Optifine, but still I'm posting this.
When using a Ressource Pack which applies a Colormap to water (see assets\minecraft\mcpatcher), Chiseled Fluid don't care and use the normal texture.
I'm trying to use [This pack](https://minecraft.curseforge.com/projects/ocean-water?gameCategorySlug=texture-packs&projectID=299401).

![2018-08-08_16 45 30](https://user-images.githubusercontent.com/27089398/43844653-8c39978e-9b2a-11e8-8f6f-a187ae2447f4.png)

**Comment by AlgorithmX2** [comment]
I'm not sure its even possible to support this without digging out how it works and copying it into my mod. Which I'm not going to do. Any mods that change how water renders won't effect how C&B renders water, since C&B is rendering water in its own way, like any other block.

Maybe when 1.13 drops when I look at the vanilla water mixing with blocks logic this might not require water bits, but for now I don't think there anything realistically that I can do.
