### ISSUE TITLE
Bit Index < 0 Crash

### ISSUE THREAD

**Issue by WenXin20** [ChiselsAndBits/Chisels-and-Bits#421]
* MC Version: 1.12.2
* Forge Version: 14.23.4.2750
* C&B Version:
* Do You have Optifine: Yes

I got this crash after loading a previously created world. I also have not used chisel and bits in this world yet.
**[Crash Log](https://paste.dimdev.org/kehuvetuvi.mccrash)**
**[Latest.log](https://gist.github.com/WenXin20/fbcee7cbddc673b366ff42e1e3d6d09f)**

**Comment by AlgorithmX2** [comment]
I'm honestly not sure how that happens, its basically saying that the state id of a block is -16

To my knowledge no state id should be negative, how many blocks do you have in your world? This might be a bug with Just Enough ID's which expands the number of states you can have.

**Comment by WenXin20** [comment]
I'm not sure how many blocks there are, but I do have a lot of mods. Is there a way to check how many blocks there are?
 I also thought the crash was weird because I have been able to use that world twice after creating it. The only thing that had changed was updating a few mods and I added in Youtuber's Lucky Blocks. Could that have shifted block ids and caused this? I was able to create a new world with no problem.

**Comment by AlgorithmX2** [comment]
Regarding block count, nothing comes to mind.

Its hard to say, It might be related to a change in mods, but its hard to say. All I know for sure is that the state id should not be negative, and since C&B doesn't generate those ( normally its vanilla / forge ) but since you have a ID Extender that's probably included I'd say something went wrong when you added the mods. Especially since new worlds are working fine.

There is a reason your supposed to back up worlds when adding mods after all...

That all said, if you want you can try [this build](https://www.dropbox.com/s/wi6seuaitpensn5/chiselsandbits-14.21x.jar?dl=1).  I attempted to patch it so that C&B "ignores" negative state ids, I honestly have no idea what will happen when you try it though, something else might explode, or something.

I guess let me know what happens if you try it out, not really sure honestly.

**Comment by WenXin20** [comment]
I do have aromabackup installed, but I don't mind losing the world, since I had just begun using it anyway. I'll let you know how the build works out, thanks.

**Comment by WenXin20** [comment]
The world worked out fine with that build, thanks.
