### ISSUE TITLE
[Issue] Chiseled aurora block doesn't act properly

### ISSUE THREAD

**Issue by TomaszewskiPatryk** [ChiselsAndBits/Chisels-and-Bits#424]
* MC Version: 1.12.2
* C&B Version: 14.21
* Do You have Optifine: Check both with and without optifine, same thing happens

When you chisel an aurora block from [Twilight Forest](https://minecraft.curseforge.com/projects/the-twilight-forest?gameCategorySlug=mc-mods&projectID=227639), it looses it's color changing abilities.
It also transforms to "Chiseled Packed Ice" and gains slipperiness, even though normal block doesn't have it.

**Comment by AlgorithmX2** [comment]
According to the source code its packed ice,  https://github.com/TeamTwilight/twilightforest/blob/7b86ed7774d16d13887947b1ef768950dd42df9f/src/main/java/twilightforest/block/BlockTFAuroraBrick.java#L27  though I can't explain for the life of me why it would be... but C&B can only do so much with trying to figure this sort of thing out. You might be inclined to ask the mods authors about this, since C&B bases a lot of the physical simulation aspects off of a blocks materials.

As for color changing abilities, can you describe what your talking about? or provide a gif or image or something? I don't have any experience with the mod to know what your talking about.

**Comment by TomaszewskiPatryk** [comment]
Oh, right, sorry about that.
Aurora block changes its color based on its position in the world and has a slight animation to it as well.
[Link to a gif.](https://i.imgur.com/gmxt6Al.gifv)
(On the left are original aurora blocks, on the right are the chiseled ones)
The animation does play, however block base color stays the same.
_I'm aware that it's nearly impossible to catch such a thing with one universal algorithm, but maybe making it an exception is worth being able to chisel such block._

**Comment by TomaszewskiPatryk** [comment]
Wait, couldn't you calculate slipperiness of the block by using the average of slipperinesses of blocks on the surface? (since these are the only blocks your "feet" will "touch")
From what I've been told at [Twilight Forest](https://github.com/TeamTwilight/twilightforest/issues/607), slipperiness is a property independent from the material.

**Comment by AlgorithmX2** [comment]
They are indeed separate things, C&B does use a simplied model with how it deals with slipperiness.

There is a reason however, and that reason is because slipperiness cannot properly be determined for a block without an entity. C&B doesn't have such complex logic. So I opted to "dumb down" the situation so that only ice is slippery, since that handles most cases.

So far there hasn't really been a case where this hasn't worked, I'm just surprised that this block is "Packed Ice" when it doesn't really seem to be related to Ice at all. Though I suppose I could be wrong.

**Comment by TomaszewskiPatryk** [comment]
Oh, you are right, I didn't think about performance, which is very important if there are a lot of those blocks (which usually is the case).

And, in case aurora blocks material won't be changed, couldn't you make a special config file in which you replace material assumed by Chisel and Bits for given block id?
This shouldn't affect performance so much and would allow you (by file default values) and modpack creators to fix such issues rather easily.

**Comment by AlgorithmX2** [comment]
Please try https://www.dropbox.com/s/tm0npaktcq2sn2g/chiselsandbits-14.22x.jar?dl=1 slipperyness and colorization should be fixed.

**Comment by TomaszewskiPatryk** [comment]
Wow, you fixed it really fast.
It looks like everything is working now.
There is one minor thing though, when you shift-hover over aurora bit or look at chiseled aurora block with waila, it's white instead of default green (same goes for grass block). But it's really just a detail.

**Comment by AlgorithmX2** [comment]
https://www.dropbox.com/s/txrn94elibytkgr/chiselsandbits-14.22y.jar?dl=1 Give that one a shot, hopefully that should have everything working as expected ( in theory )

The whole ice thing should be good as well if you haven't tested that yet. You can close the other issue, I found a good way of dealing with slipperiness by updating to a slightly more recent build of forge.

**Comment by TomaszewskiPatryk** [comment]
Yup, everything works now.
