### ISSUE TITLE
[suggestion] Vanilla-shaped preset templates

### ISSUE THREAD

**Issue by loudwhitenoise** [ChiselsAndBits/Chisels-and-Bits#430]
I'm fond of using this mod to make artificial staircases or fences from blocks that were never given those shapes. I make use of the positive and negative designs while doing so. 

My idea is to craft a vanilla 'shaped-block' (eg fence, stair, wall) with a design to make an equivalent to that block but in bits.
This could allow us to swiftly make, for example, a negative design shaped like a cobblestone wall that I could then use on anything I want. 

I can see one issue with this is the blocks I'm talking about have multiple connectivity-based states and you'd have to pick just one, probably the middle state.

**Comment by AlgorithmX2** [comment]
The middle state of a wall is just a pole, I'm not really sure that this is a functional idea once you get past the "Sounds neat" point.

The same for stairs honestly, you might get a normal stair case. However in reality chiseling a stair case by hand is only 1, 2, or 3 clicks. Since you can just use the largest grid snapped cube to take out.

It also fails to consider resource packs. Since those could technically alter the shapes of the blocks in question.

All in all the more I think about it, I just don't see it really being much help.
