### ISSUE TITLE
Server disconnects on first login attept after initial load up of pack.

### ISSUE THREAD

**Issue by SniperHauss89** [ChiselsAndBits/Chisels-and-Bits#448]
* MC Version: 1.12.2
* C&B Version: Latest 14.29
* Forge Version: start with the recommended version (2768) and then updated to the latest version (2796).
* Do You have Optifine: No
Description of the problem:
Every time I load up the pack for the first time and go to load into the server it disconnects on the first try and says "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host."
This was also an issue with Advanced Rocketry recently and was fixed. It had to do with packet handling of some sort. I have up until recently had no issues with C&B and love the mod.

**Comment by AlgorithmX2** [comment]
What makes you think that the issue is caused by C&B, and can you provide any details of the the exception from your logs, possibly the log itself? What pack are you using?

Are you using the correct amount of memory for the pack? Some packs are pretty large, and might need a considerable ram allocation to run properly.

With current information, even if it is C&B, there is no way I can reproduce the issue to track down an issue.

**Comment by SniperHauss89** [comment]
Ok, so first I just want to say I'm sorry for pointing the finger at your mod. It was late and I was tired I will admit and as a result I didn't do my trouble shooting properly thus leading me to this false conclusion. I had been working on update my modpack (a custom one made for me and some friends) and had been at it for awhile and so I wasn't thorough as I should of been. Anyway again I am sorry for this and will close this issue promptly.

**Comment by AlgorithmX2** [comment]
No worries, good luck sorting out your problems.
