### ISSUE TITLE
Some chiseled blocks don't retain properties?

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#464]
Hello, i noticed that when i chiseled obsidian and tried to break it by hand, it would take an extremely long time, but when i chiseled a piece of 16x compressed obsidian from Overloaded and tried to break it with your hand, it would take a MUCH less amount of time. I was wondering if you could fix this, or is it not possible?
Thanks.

EDIT: Also, just wanted to mention that the 16x compressed obby has a hardness value of about 9 trillion (9,000,000,000,000) i believe.

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: chiselsandbits-14.30
* Do You have Optifine: Yes

**Comment by AlgorithmX2** [comment]
This is likely because Overloaded handles its hardness values in here 
https://github.com/CJ-MC-Mods/Overloaded/blob/1.12/src/main/java/com/cjm721/overloaded/block/compressed/BlockCompressed.java#L137

This function takes a World, which is a bit of a problem compatibility wise with C&B. Since C&B can't call this method with its own block ( a lot of mods could crash that way ) and emulating a full world is beyond what I consider reasonable for the mod.

I can't use the method. I have to pull the hardness value from block value, which in this case dosn't take into account the block very well.

I'm afraid there isn't much that can be done to support this.

**Comment by ghost** [comment]
Alright, it's good to know. 
Thanks for the info and the mod!
