### ISSUE TITLE
Chisels can only be used once in survival mode.

### ISSUE THREAD

**Issue by Syphenion** [ChiselsAndBits/Chisels-and-Bits#465]
Chisels (any type) can only be used once on any block. After chiseling the block once, I cannot chisel it any more without going to creative. The issue does not occur in creative mode. I have chisel durability turned off. There are no crashes or errors reported, might be a config error on my end.
 
* MC Version: 1.12.2
* C&B Version: 14.32.
* Do You have Optifine: Yes

**Comment by AlgorithmX2** [comment]
I turned off "damageTools" under "balance settings" and I'm not seeing any problems. Is this the setting you are using? or are you referring to something else?

**Comment by Syphenion** [comment]
Yeah that's the setting I used, but I have no actual idea what's causing the bug, I'm just guessing. Even with a brand new config file, I still get the same error.

**Comment by AlgorithmX2** [comment]
I'm not really sure myself are you using other mods? It might be another mod causing the issue since my instance which is just C&B seems to be working fine.

**Comment by Zeoic** [comment]
I am running into the same problem. I can build with bits, but I can only remove bits once from blocks. As soon as it turns into a "Chisled Bit" I can no longer remove bits from it. This only happens when you are on a dedicated server, and in survival mode. creative mode and singleplayer work just fine.

- MC Version: 1.12.2

- C&B Version: 14.33

- Modpack: All The Mods 3 Expert Shedding Tiers

- Do You have Optifine: No

**Comment by Aeltumn** [comment]
Please create a new issue for this instead of commenting on this old one. However, this issue was unable to be reproduced so it's likely this issue is due to another mod in which case you should report it to them.

**Comment by mcircuit** [comment]
Can someone tell me where to find the balance settings? I cant seem to find it anywhere...
