### ISSUE TITLE
Query about blocks from other mods

### ISSUE THREAD

**Issue by hotluck** [ChiselsAndBits/Chisels-and-Bits#466]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.32
* Do You have Optifine: Yes

I use Railcraft and have found that Quarried Stone will not work. I checked the config and found that some railcraft items are in there but not that one. I tried adding it but it still doesn't work so I am guessing I haven't done it right. This is what I added -

B:mods.railcraft.common.blocks.BlockQuarriedStone=true

What should it be?

Also, I use Architecturecraft. Would your mod work on items made with that mod from quarried stone if the quarried stone item was added correctly to the config?

P.S. Not sure what MCMP does and whether it is relevant. If it is, please let me know as I don't have that installed.

**Comment by AlgorithmX2** [comment]
Unfortunately the Quarried Stone in RC is implemented with a "generic" block that overrides methods that C&B checks for compatibility. Because those methods are overwritten, C&B marks it as not compatible since it doesn't know what the code inside the method actually does.

The black/white listing feature dosn't override this, since it can cause unpredictable results and crashes.

However you can request that they use the C&B IMC to enable support if you want.

Here is a simple example of how Tinkers Construct does this, https://github.com/SlimeKnights/TinkersConstruct/blob/40636feb7233a10d33d288345b68af6a452373ab/src/main/java/slimeknights/tconstruct/plugin/ChiselAndBits.java#L32

**Comment by hotluck** [comment]
Thank you for getting back to me about this.
