### ISSUE TITLE
[1.12.2][14.32] C&B Blocks Cannot Be Placed Via Automation/Fake Players

### ISSUE THREAD

**Issue by Aedda** [ChiselsAndBits/Chisels-and-Bits#468]
I've discovered that blocks made with C&B cannot be placed by fake players such as Turtles, Robots, Block placers, etc. The former two (which have feedback) report the block as successfully placed however a block never forms. There are no errors reported in the console even with debug configs turned on.

I seem to remember this working in the past. It was very disappointing to discover it did not work.

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.32
* MCMP Version: 2.5.3
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
Please try this build, it appears that a fix I made quite some time ago related to shift-click placement broke this. No one has reported it since.

https://www.dropbox.com/s/7681ghwcpev5xmq/chiselsandbits-14.33.jar?dl=1

**Comment by Aedda** [comment]
Yep that works a treat, you rock!

**Comment by Aedda** [comment]
Turtles seem to be acting a little weird yet (but robots and block placers both seem to work). They sometimes place the block and sometimes fail but it seems random and like it suddenly resolves itself and then works for a while afterward. Might be something on their end. I've been trying to duplicate it reliably but so far it only happens when I'm not expecting it to.

**Comment by AlgorithmX2** [comment]
https://www.dropbox.com/s/7681ghwcpev5xmq/chiselsandbits-14.33.jar?dl=1 ( well its the same link, just a new file )

Here is a new build, I think I fixed it.

**Comment by Aedda** [comment]
Been playing with it for a bit and cannot seem to get it to fail, 100 out of 100 turtles successfully placed their block. Curious what did you change the second time?

**Comment by AlgorithmX2** [comment]
Two things, for some reason it was failing to get the tile entity after it created it and added it to the world. Still not sure why that was happening, has something to do with how chunks/world tile lists work, and I honestly figured that there was no real fix in that direction. So I just returned the TileEntity it created form a method and used that one instead, that fixed the strange random failures.

The second change was to fix the return value on the use item command seems like I had it returning false regardless, probably because this whole thing works a little strangely for normal players. That fixed the success/fail result of the turtle place method.

Its honestly sort of a mess, but it works.
