### ISSUE TITLE
Cant match two blocks with biome colors when Chiseled

### ISSUE THREAD

**Issue by ricey125** [ChiselsAndBits/Chisels-and-Bits#492]
Hello, I am using conquest reforged mod along with C&B. Ive noticed that diorite and stone do not retain their swampland color when chiseled while grass and leaves do. I was wondering if there is a simple fix for this?
MC Version: 1.12.2
C&B Version: 14.33
Do You have Optifine: Yes
Conquest Reforged: 3.0.2-mc1.12.2

**Comment by Aeltumn** [comment]
Diorite and stone do not have different colors in the swamp biome normally. If conquest reforged adds that functionality it's a problem on their end.

**Comment by ricey125** [comment]
Got it, Ill take it up with them then. Also what does the revertible block list mean?

**Comment by Aeltumn** [comment]
I don't know what revertible block list you're referring to?

**Comment by ricey125** [comment]
![2020-01-17_11 04 50](https://user-images.githubusercontent.com/59389256/72638897-4c94b080-3919-11ea-9675-91d3540eb665.png)
Sorry, revertible states.

**Comment by Aeltumn** [comment]
IIRC this list can be used to prohibit blocks from turning back into a full block. I don't know of any uses for it and it doesn't exist anymore in C&B2.
So if you had stone on this list and you chiseled stone then placed the bits back so it's a full cube it would still stay as a chiseled block instead of turning back into a stone block.

**Comment by ricey125** [comment]
Ok, thanks :)
