### ISSUE TITLE
Light level modification not tied to bit contents.

### ISSUE THREAD

**Issue by nnystyxx** [ChiselsAndBits/Chisels-and-Bits#55]
I'm not aware of the metadata/data associated with a chiseled block, but would it be feasible to make a chiseled block have a light level independent of its contents or the number thereof-- like making a block that glows with no glowstone in it, or, in an advanced implementation, causing a block containing glowing blocks (a la Flat Colored Blocks) -not- to glow? 

My reasoning behind this: I have my % of light blocks required set very (VERY) low, so that I don't need much glowstone to make a lamp light up, but at the same time, using the glowing blocks from Flat Colored Blocks will cause something to be much brighter than I want it to be when I inlay a glowing design on it. One amount is too much for one, and too little/just right for the other. Does that makes sense?

Example: Place a wooden lump you want to glow. Use the Meta-Modifier(tm) to change the light level associated with the chiseled block. It now glows at light level 7, for instance, or whatever was picked.

**Comment by AlgorithmX2** [comment]
I suppose you can actually run into this problem regardless of your "bits required for light level" settings, since you might want a block compromised of large amounts of glowstone to glow, but not emit light, or for a block with almost no bits to emit light ( be a light source ) for instance.

I might need to add a new tool.. and maybe require coal or glowstone dust to adjust the value up or down accordingly however.

**Comment by nnystyxx** [comment]
I appreciate the response. I'm racking my brain but can't really think of other in-block values worth modifying other than something like 'effective height' or 'slipperiness' or the like. I suppose that's treading more into direct, cloaked functionality. Anyway, things that glow even though they "shouldn't" are an interesting design trope. Could be used for things like subtle light sconces, etc.
