### ISSUE TITLE
Top-Layer Water Merges With Actual Water

### ISSUE THREAD

**Issue by irkedIsaac** [ChiselsAndBits/Chisels-and-Bits#56]
If the top pixel layer has water on it, it should blend with the regular Minecraft water level (which is slightly higher...for no reason). Alternatively, it should do that if the sculpture is surrounded by water.

**Comment by AlgorithmX2** [comment]
Minecraft water has 1.8-1.9 or so pixels of air in its block, there is no clean way to deal with this, and if I move the water, then you can't make the non-water bits match the solid bits, because they would be higher then the solid bits around them.

In addition to that adjacent water blocks and bits do not cull the faces between them, since bits are not actually water, and water is not bits; while I could potentially cull faces on the bits, I can't do so on the water.

I'm not sure that fluids and fluid bits will ever be able to blend seamlessly, both of these issues have no simple answer, and if I were to make random adjustments like changing the geometry of the water bits under certain arbitrary conditions might lead to bad results, "I tried to make a puddle and the water bits disappeared and are rendering under ground." or something strange like that.

**Comment by irkedIsaac** [comment]
Fair enough, it's just a small pet peeve that I only really noticed when I looked at a particular sculpture very up-close. Thanks for the answer!

**Comment by AlgorithmX2** [comment]
Wish it was more straight forward, its just one of those odd ball things.. I wish there was a better solution, but I don't have one unfortunately.
