### ISSUE TITLE
No amount of bits emits light.

### ISSUE THREAD

**Issue by Tsunamori74** [ChiselsAndBits/Chisels-and-Bits#571]
MC: 1.16.4
Forge: 35.1.28
Optifine: HD U G5
C&B: 0.2.8R

Blocks stop emitting light after a single bit has been removed, with default settings or after setting bit percentage to either 1 or 0. Updating light calculations in the surrounding area or relogging don't seem to affect the situation.

**Comment by TheDrumkid92** [comment]
Having the same issue. Playing on a server.
MC: 1.16.4
Forge: 35.1.37
Optifine: HD U G6
C&B: 0.2.10

**Comment by Vvarbanov** [comment]
Having the same issue.
MC: 1.16.4
Forge: 35.1.37
Optifine: HD U G7
C&B: 0.3.4R

**Comment by marchermans** [comment]
Optifine is not supported.
And certain features can not be guaranteed if it is installed.

**Comment by Tsunamori74** [comment]
Why do you ask people to state wether they have optifine or not when making a report then? Just state outright that it's not supported and reports with optifine related issues will be ignored

**Comment by marchermans** [comment]
Because some people will do it regardless. And in some instances optifine works. But in others it does not. 

Yes I indeed should need to clarify that.

**Comment by JohnathonCurrie** [comment]
@OrionDevelopment 

> Optifine is not supported.
> And certain features can not be guaranteed if it is installed.


Is their any new compatible versions with Optifine? Or plans for such; as [#589](https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/589) is also having the same issue describing part of the issue that I've now spent 4 hours trying to fix / make sure their wasnt an awnser somewhere else [Their is not; its just 'will be fixed in future releases']. 

I ask because this was a problem for [#286](https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/286) and was later going to be fixed. Only to find out [#474](https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/474) the main Dev is retired and since you picked up his shoes you got to fill them.

I have no idea what version of Forge+Optifine+C&B I need to get / is compatible. Doesn't even say anywhere on the main site or any 3rd party rip off that ' Optifine is not supported '
I mean like @Tsunamori74 said. No point in asking if they use it or not if its not compatable. So don't be lazy, fix the [FAQ](https://chiselsandbits.github.io/Chisels-and-Bits/frequently-asked-questions/) page. 
Even go a step in the right direction for all those who didn't bother to try to fix it; by letting people know what the most up to date software / minecraft you need.
