### ISSUE TITLE
block types changes between pack updates

### ISSUE THREAD

**Issue by Sunekaer** [ChiselsAndBits/Chisels-and-Bits#578]
FTB Presents Direwolf20 1.16

So i installed version 1.2.0 of the pack placed down some bits of two blocks updated to 1.3.1 and the bits had changed to another block, but keep the bit id

`undergarden:smogstem_leaves` changed to `create:layered_dark_scoria` (`chiselsandbits:block_bit {id:301174}`)
`comforts:sleeping_bag_white` changed to `undergarden:grongle_planks` (`chiselsandbits:block_bit {id:214425}`)

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: tried .8 and .9
* Do You have Optifine: No

https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/54

**Comment by NielsPilgaard** [comment]
Same thing for Enigmatica 6.

**Comment by marchermans** [comment]
Fixed in 0.3.0

**Comment by gtosh4** [comment]
Will the fix apply retroactively (ie, my blocks are already swapped after updating to Direwolf's latest version which is only 0.2.10) or will I have to fix it again after updating to 0.3.0 but it won't occur again on subsequent upgrades.

**Comment by marchermans** [comment]
Well it is an update to the storage mechanism.

So what happened is that when you update _other_ mods, the block id table shifts from which C&B reads the bit data. Now with this version I added a palette (the same system chunks use to store what blocks are inside them). When you install this update, C&B will read, one last time, from the block id table **that you have installed at the moment of the update** the data and then convert that data into the new paletted version. So from that moment onwards it does not directly depend on it anymore and changes to the layout of the block id table do not cause changes in the bit data anymore.

That said, if you now **only** update C&B to the new version, then it will take the state of your world as it is _now_ before your update. But if you update C&B with other mods, there is a chance that the block id table changes and then C&B performs the migration with this changed table. This is something I can not prevent, due to the fact that the old mechanism from which I ported C&B depended on that table and I had no direct idea on how to fix that untill this update.

_**Additionally this update migrates the data in an unreversable way!**_ That means that once you update, there is no way back.
