### ISSUE TITLE
Positive Chisel Design object dissapears after single use

### ISSUE THREAD

**Issue by Tallivm** [ChiselsAndBits/Chisels-and-Bits#582]
* MC Version: 1.16,4
* C&B Version: 0.2.9
* Do You have Optifine: no

After getting Positive Chisel Design - Written (on chiseled vanilla block), and setting it to Placement, after placing the block, Positive Chisel Design disappears from my inventory.
Impose, Additive and Replace work as expected.

**Comment by khan-22** [comment]
I want to add that I experience this as well. Although _sometimes_ the design doesn't actually disappear but becomes invisible in my inventory. Sometimes opening and closing a bag will make the design reappear but this doesn't always happen. This also happens to me frequently when destroying a design with a tool and picking it up in my inventory (it becoming invisible and randomly reappearing).

**Comment by kainelowen** [comment]
Having the same issue on an All the Mods 6 server with 2.9 installed.

**Comment by IrisEdelsmid** [comment]
I also experience Positive chisel design disapears when using to place designed block,  previous C&B version though, so just to clarify this issue was in C&B 0.2.8 too.
I think this issue could be related: 
I also experience the Positive chisel design + chiseled bits bag with contents disapears when using in crafting bench to make designed block.(both adjusted design and back to vanilla block design.)

- MC Version 1.16.4 
- C&B version 0.2.8
- Do You have Optifine: no
- modpack direwolf20 1.2.0 (yes i'll update)

**Comment by Goshujinsama** [comment]
Also running into this issue.  Running on Creeperhost hosted server.  Pattern is consumed when used in placement mode.  Have tried restarting server and other such diagnostic tasks.  Does not reappear in inventory.  It does not appear be a sync/rendering issue.

Minecraft version 1.16.5
Modpack: FTB Presents Direwolf20 1.16 (version 1.6.1)
Optifine: No
Chisel and Bits version 0.2.10-RELEASE

**Comment by Veritas52** [comment]
Experiencing the exact same issue.

Minecraft 1.16.5
Modpack: Valhelsia 3
Optifine: No
Chisels and bits 2.10 Release

**Comment by TheDrumkid92** [comment]
Same issue

MC: 1.16.4
Forge: 35.1.37
Optifine: HD U G6
C&B: 0.2.10

**Comment by marchermans** [comment]
Fixed in 0.3.1-Release
