### ISSUE TITLE
Incorect placement when trying to place off grid

### ISSUE THREAD

**Issue by CivilNikolas** [ChiselsAndBits/Chisels-and-Bits#585]
Similar to #575 which is now fixed

When trying to place a chiseled block off grid (by holding the assignrd key) the block is placed one bit higher than it should.

 * MC Version: 1.16.4
* C&B Version: 0.2.9
* Do You have Optifine: yes (also tried without)

**Comment by MCaesar** [comment]
Just had the same issue. Placing a bit always places +1 along the (x/y/z)plane, leaving a space in the spot you actually wanted the bit. Trying to place a line or plane ends up +1 block along the (x/y/z)plane.

C&B: chiselsandbits-0.2.8-RELEASE
MC 1.16 Direwolf20 1.3.1
Optifine: No

**Comment by CivilNikolas** [comment]
The wrong placing of bits has been resolved in the next version of the one you are using (0.2.9). What i experience happens when trying to place a whole block tha has been chiseled and only when trying to place off grid.

**Comment by iainvm** [comment]
I'm currently seeing this

So I made a flower in a pot, made when I pickaxe the object and get the block I wanted to place it not a layer up, so placed down the layer, but when using the `place off grid` feature the flower pot is an entire block above, instead of on the layer I placed. Even though the shadow render showed it on the layer. 

Minecraft 1.16.5
Forge 36.1.0
Chisel and Bits 0.3.4

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
