### ISSUE TITLE
2 and a half bug :3 

### ISSUE THREAD

**Issue by AndriSve** [ChiselsAndBits/Chisels-and-Bits#635]
Ok so first is the preview with sawed block that does some weird thing.
second is when placing/removing first bit from whole block causes texture to flicker and then appear different like its rotated or something.
third is the names for the sawed blocks which isn't really a bug, just annoying.

here's the video
https://youtu.be/4OfK-6WXBIk

* MC Version: 1.16.5
* Forge version 36.0.54
* C&B Version: chiselsandbits-0.3.4-RELEASE.jar
* Do You have Optifine: no

**Comment by marchermans** [comment]
With regards to your issues:

1) I don'T see anything wrong in your video. The placement behaviour is normal, it placed where the preview was when you clicked.
2) The texture thing is not actually a bug. Some textures in minecraft (notably world gen ones, like stone and grass) get randomly rotated around. When you created a chiseled block from them, they revert to the default texture orientation. Which i sadly can't really prevent.
3) The names are indeed a bug and I will try to fix them.

Can you explain 1) a bit better? Like what did you expect to happen? What did happen? What did not happen but you think should happen? etc.

Greets Orion.

**Comment by AndriSve** [comment]
for starters I didn't expect it to overlap with that part since it was already fully occupied and rather snap to the surface allowing me to convert 1pixel thick into a full block slowly just like with snow but sideways. Anyways it just looks buggy when you see it overlap with a block that's there. "it shouldn't show a transparent preview inside the block when its already there is what I mean. But rather just highlight it like normal blocks that you look at."

**Comment by marchermans** [comment]
By default the placement mode is: _Fixed_ Placement. Meaning that the blockplacement at hears to what you hold in the stack based on the block that you are looking at, this means that the cut block (which is nothing more then a block you chiseled in reallife in the way you cut it) is placed at the border.

Now if you want this behaviour disabled. Press shift, this enables _Offgrid_ Placement, and allows you to place the cut piece anywhere, including making a "full" block out of tiny sections.

The overlapping happens, because technically these blocks are mergable, since they are made up out of none colliding bits (aka air or the same block in the target as in the itemstack). So the system renders to the see through box.

With the fixes in 0.3.5 to rendering and placement logic, I consider this ticket closed.
