### ISSUE TITLE
Can't load the preview of chisel design(Positive/Negative/Mirror) 

### ISSUE THREAD

**Issue by creamIcec** [ChiselsAndBits/Chisels-and-Bits#702]
* MC Version:  1.16.5
* C&B Version:  chiselsandbits-0.3.4-RELEASE.jar
* Do You have Optifine: Yes
![chisels design](https://user-images.githubusercontent.com/42510470/127254452-c169c24e-f803-4ba7-9d6c-68b5783c2e82.png)
When I hold a chisel design(such as a positive chisel design) and face a block, I can't preview the chiseled block, which means the angle of this block I'm gonna place is invisible.
I tried to disable Optifine but this still happens.
Perhaps there is a hotkey to trigger it?How can I fix this?

**Comment by Tony322** [comment]
Same issue using version chiselsandbits-0.3.4-RELEASE on 1.16.5. 
Optifine? NO

**Comment by marchermans** [comment]
Hmm can you send me the log?

**Comment by holyaurora21** [comment]
same issue also if i did try use the design it would some times place it as stone if i tried to use it. 0.3.4 1.16.5 minecraft
also a issue with mirroring designs it wont combind with negative/positive, just gives out a blank design. The only way to see the outline of placing is by going creative and middle mouse the block you have made.

**Comment by Tony322** [comment]
> Hmm can you send me the log?

Sure, but I'm not sure which log. Server log or client log? Do chisel n bits have their own log file?

**Comment by creamIcec** [comment]
Sorry I just cleaned my logs a week before.
I'm gonna reproduce this bug and then I'll send the log.

**Comment by creamIcec** [comment]
It is strange when I tried to use the chisel design there weren't any logs printed.
I tried to search in the log file for anything about this issue but I can't find anything.
Sorry, I can't provide the log.
Please note this is for the 0.3.4 version of chisels & bits.

**Comment by marchermans** [comment]
This will like not be fixed anymore in a 0.x version.
This will only be fixed in a 1.x rebuild version

**Comment by marchermans** [comment]
Implemented in 1.0.8 rebuild.

**Comment by LindaJuffermans** [comment]
Please fix this feature in 0.x, the 1.x version is impossible to work with for now.

**Comment by marchermans** [comment]
Sorry no. 0.x is by definition out of support. Why is the new version impossible to work in?

**Comment by LindaJuffermans** [comment]
Because with `chiselsandbits-1.0.12-RELEASE-universal.jar`:

The radial menu is unreadable on GUI scale 2:
![2021-10-11_20 45 57](https://user-images.githubusercontent.com/31929183/136839311-0fc018b0-b35c-4e5e-9e70-f0b227ac1f20.png)

There is no region draw for larger areas.

It fills my inventory with bits eventho I have the bag:
![2021-10-11_20 53 04](https://user-images.githubusercontent.com/31929183/136840097-d59ecaa9-efbb-45d8-b660-eaaf5a23df31.png)

Sometimes there is no preview shape at all (this should show a 1/2 size snapped rect):
![2021-10-11_20 52 10](https://user-images.githubusercontent.com/31929183/136840804-c776a90f-7ede-4997-bc5c-9b7dbf019ab1.png)

Sometimes the preview is not placed on the surface I'm looking at but instead floating mid air:
![2021-10-11_20 52 27](https://user-images.githubusercontent.com/31929183/136841386-1c0f20c8-e824-474f-b5ac-97bc5166baec.png)

It leaves ghost blocks (see Waila):
![2021-10-11_20 55 43](https://user-images.githubusercontent.com/31929183/136842397-43dae80e-f7e8-436c-8216-7d45fcc19e61.png)

As a result I cannot place this line facing me:
![2021-10-11_20 56 31](https://user-images.githubusercontent.com/31929183/136842446-d2384d56-340f-47b5-99c5-290e018b05af.png)

(I'm not a fan of the new pattern system - I loved making designs on the fly and recyling them when needed - but that's more personal preference than a bug.)

Don't get me wrong tho, I love your mod - I've spent tons of hours chiseling decorations in the past. Right now, I'm not sure if I want to use it for this pack.

**Comment by marchermans** [comment]
Why did you not report those things?
I can't fix stuff which i am not aware of

**Comment by LindaJuffermans** [comment]
I only started using it today and considered but was too busy - and honestly, frustrated that I couldn't continue my project - so instead I reported that this feature is greatly missed in 0.x

**Comment by LindaJuffermans** [comment]
FYI: The missing or misplaced preview was also down to ghostblocks.
After removing them in creative mode, that was resolved.
