### ISSUE TITLE
Chisel fails to interact with vanilla blocks.

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#756]
Whether I'm in survival or creative mode, using the chisel on any block that isn't grass, water or lava will result in the chisel refusing to work. It will not take out the bit or even show the overlay of the block being looked at at all. 

Extra info:
* MC Version: 1.16.5, forge 36.2.0
* C&B Version: 1.0.12 RELEASE-universal
* Do You have Optifine: No, but I do have ports of Lithium and FerriteCore.
Full modlist: [modslist.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7316126/modslist.txt)

**Comment by ghost** [comment]
This is caused by an incompatibility with Lithium. 
https://github.com/jamierocks/lithium-forge

**Comment by marchermans** [comment]
This is a problem on the Lithium side of things.
They assume the world of the explosion check is none null.
Be aware that RoadRunner (A different Lithium port then the one you use, has this fixed)

However I still provide no support for people using these mods.
So report it if you want it fixed in your particular port of lithium or switch.,
