### ISSUE TITLE
blocks took TOO LONG to load up

### ISSUE THREAD

**Issue by ink717** [ChiselsAndBits/Chisels-and-Bits#776]
Minecraft 1.16.5, Forge 36.2.4, Chisel 1.0.38 Alpha
Still, the same problem seems even to take longer. Whenever I teleport to a place where a large number of chisel blocks are present, everything is transparent, and it took 30 seconds-1 minute till all the blocks show up.

This is causing too much chaos right now even it's still in my testing server. Is there a config option to change this or its currently a bug, or the desired behavior?

**Comment by CptPICHU** [comment]
This is known and Orion will adress it - if possible - eventually

It is mainly because when chunks with C&B Data are loaded, much more data need to be loaded.
When your PC is slow, or even running MC and the Server at the same time your CPU might be suffering a little. Thats why it might take so long. At my PC it takes like 3-5 Seconds when the chunks havent been loaded for a while.

Take a note: If you run your Server and MC at the same time on the same PC, that can take a lot of resources.
But maybe Orion can help you out more.

**Comment by marchermans** [comment]
Accurate description

**Comment by ink717** [comment]
I have a dedicated PC with i5-10400 and 32GB of RAM + SSD for running that server. My machine is an i9-10850K, 32GB RAM, RTX3090. It took me at least 30 seconds for stuff to load up - it never happened in 0.3.4 and before. Is it due to the intense amount of chisel blocks we had to build? I didn't notice any big differences between performance across the 2 versions but considerably longer block load. 
As of right now I activated the backup of the world and returned to 0.3.4, keep updated when there's the solution.
It's completely understandable as the mod is still being actively developed and fixed, but do have questions like this as a concern.

**Comment by marchermans** [comment]
Can you send me some screenshots of your world?
Cause I am trying to figure this out, and I can't.

It might be related to the complexity of your environment.

**Comment by ink717** [comment]
![Uploading 2021-11-16_14.56.15.png…](
![2021-11-18_18 56 25](https://user-images.githubusercontent.com/72815511/142515427-2243f578-1ab9-4c8a-b3a6-18e727e2313b.png)
![2021-10-01_01 41 37](https://user-images.githubusercontent.com/72815511/142515449-ab6d4599-d025-41e1-98b7-c096012a809f.png)
)

that's the city of newton where the most chisel blocks were concentrated. Same for other cities/places, the airport usually had the MOST amount of chisel. all lighting in the airfield except green/blue lights were made by chisel. Cuz that's where modded airplane takes off and land, it became the place where no one wants any lag or chunk delay at all.
I really can't think of anywhere else that has more chisel blocks other than airports. 

Here is a mod list, not sure whether it's helpful. Some mods do cause incompatibility with either shaders or chisel but they were rarely or never used.
[list of mods 2500b.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7566814/list.of.mods.2500b.txt)

**Comment by ink717** [comment]
![2021-11-18_19 06 37](https://user-images.githubusercontent.com/72815511/142516124-ca7d9811-f2e2-4872-942a-3cd7873cf069.png)
![2021-11-18_19 06 06](https://user-images.githubusercontent.com/72815511/142516212-a6805c24-e5c9-4030-9b51-e0348343c34c.png)

**Comment by marchermans** [comment]
Yeah. I checked it out,

There is not much I can do.
C&B has to compute the models somehow at some point in time. 

So I can either hold the chunk load and make your game stutter, or compute them offthread and then render them when done.
This last option seems to be better, however I updated some rendering in 1.18. Sadly world updates are not really possible due to how Mojang handles it at the moment.
