### ISSUE TITLE
[1.10.2] startup logs filled with RFTools & Chisel and Bits related errors

### ISSUE THREAD

**Issue by Da-Technomancer** [ChiselsAndBits/Chisels-and-Bits#80]
I reported this first on the RFTools github, and was told to report it here as well.

The startup logs for minecraft contain ~400 lines similar to this one:
[22:45:59] [Client thread/INFO] [chiselsandbits/]: Unable to determine blocks eligibility for chiseling, mcjty.rftools.blocks.spawner.MatterBeamerBlock attempted to load mcjty/theoneprobe/api/ProbeMode
All of the blocks mentioned are part of RFTools.

Blocks mentioned in this manner are: BoosterBlock, ElevatorBlock, GenericBlock, EnderMonitorBlock, 
EndergenicBlock, BlockProtectorBlock, MatterBeamerBlock, SpawnerBlock, EnvirenmentalControllerBlock, PowerCellBlock, BuilderBlock, SpaceChamberControllerBlock, SensorBlock, InvCheckerBlock, RedstoneRecieverBlock, RedstoneTransmitterBlock, CounterBlock, SequencerBlock, ScreenBlock, SimpleDialerBlock, MatterTransmitterBlock, MatterRecieverBlock, ModulerStorageBlock, & CoalGeneratorBlock.

I don't know if this is important or not, but I thought I would report this.

**Comment by AlgorithmX2** [comment]
These log items are just informational, and at some point RF tools will probably use the annotation to fix the reflection accesses, but either way its not really an issue that needs addressing.

I'm going to go ahead and close this issue because there is nothing I can really do on my end to remove them besides disabling the logging, which has proven to be quite useful to find issues with C&B compatibility with several other mods.
