### ISSUE TITLE
Clipboard Item Modifiction

### ISSUE THREAD

**Issue by Dickovski** [ChiselsAndBits/Chisels-and-Bits#90]
Love the clipboard and love the Mod.  However the clipboard appears to collect every item created even those that are not wanted, and I use the chisel alot.  Any chance of a delete option and also a re-arrange option so that I can group similar objects.

**Comment by AlgorithmX2** [comment]
You might want to disable the "auto collection" options in the C&B client config and use the "add to clipboard" key-bind to only store exactly what you want.

As far as re-arranging I'm not sure, since i'm using the creative inventory its just a list, there is no way to move them around or delete them.

The features is mostly to keep track of recent things your working on, if you want more permanent and customizable storage you might be better suited to use a chest of chiseled blocks or patterns.

**Comment by Dickovski** [comment]
Yes, I guess doing what I was doing before and carrying around a set of colour coded backpacks with collections of items made using your mod and other useful bits and pieces.  At least I have the clipboard to go back to if a backpack gets dropped or deleted by mistake - I was storing them in a building, stuck on the walls.  I'll investigate the "copy to clipboard" key-bind option.
