### ISSUE TITLE
Wand of equal trade for bits

### ISSUE THREAD

**Issue by Prospector** [ChiselsAndBits/Chisels-and-Bits#91]
pls. would be so useful to just swap out all bits of one block to another.

**Comment by AlgorithmX2** [comment]
I'm currently debating the best way to implement this type of feature.

I already have a plan to add a way to replace bits when placing, https://github.com/AlgorithmX2/Chisels-and-Bits/issues/61 if I could "Lock" changes to a single bit this would work rather well.

Theres also the possibility of doing something like making a positive pattern and filtering by type, then using a negative pattern and Implace mode to overwrite them.. thats probably more complicate then it needs to be tho even if its doable that way...

**Comment by UberAffe** [comment]
Would it make sense to have some method of interacting with a pattern that shows the pallet of bits and it would let you replace bits.

Example:
You designed a tiny tree using oak bits and oak leave bits.
you go into this gui and and see your inventory and a separate place with the pallet of bits,
(as well as the design itself?)
drag a dark oak bit from your inventory to replace the oak bit.
Now the design creates a tiny dark oak tree.

**Comment by AlgorithmX2** [comment]
I've thought about editing the pattern, and it might also make sense. But I'm still not sure I like the idea, I try to prefer in world solutions to gui based ones.

**Comment by UberAffe** [comment]
If you want in world then a swapping wand would probably be the best option. Maybe give it a radial menu like the chisel but for swapping. Also being able to select "swap all" of a type or "swap all connected" of a type would be useful.

**Comment by AlgorithmX2** [comment]
I've actually put something together,

https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/50/artifact/build/libs/chiselsandbits-12.0.50.jar (update 3)

It needs some alpha testing however. I added two new modes related to material, and a replacement option on the chiseled bit radial menu.

If anyone wants to try to alpha test it.

**Comment by UberAffe** [comment]
Ooh, I can try to squeeze some alpha testing in.

**Comment by Builderb0y** [comment]
My two cents on this idea: I think an easy to implement, yet very powerful tool for this job would be to add a new mode to positive designs that acts like impose mode, except that it wouldn't replace air bits with anything else. This would allow you to replace a block with a different material while preserving its shape, replace only specific sections of a block with a different material, and replace things with multiple materials at once in a specific pattern, all in one mode.

This can technically be done by using a combination of impose mode and negative designs, but this idea makes things a lot more convenient; especially when replacing a large build with lots of different shapes with a different material, as it means you don't have to clear and re-program the negative design for every block.

**Comment by AlgorithmX2** [comment]
@Builderb0y the modes I mentioned above are already ready for testing, I'll probably be releasing in an alpha soon. those modes are attached to bits allowing you to replace entire materials in a block, as well as replacing planes and other things.

**Comment by Builderb0y** [comment]
I tested that version, and while it does have the ability to replace one material with another using the "same material" mode, it does not have the ability to replace one material with multiple others in a pattern. For example, making a statue checkerboard-ed. Perhaps pictures can do a better job of explaining what I mean: http://imgur.com/a/5tEkW

**Comment by AlgorithmX2** [comment]
So you want some kind of replacement mode for positive patterns? This Is very different from the original request. Is this really something that happens a lot? seems like you could just build the shapes, create the final patterns then place them down.

More of a initial step so you can create your final building design, rather then building the whole thing in stone, then going back and replacing the whole thing with some pattern.

**Comment by Builderb0y** [comment]
In my case, it was for applying wallpapers to the inside of my house. The windows have an indentation around them, which made working around them a bit tricky, since there were 8 unique shapes for the sides and corners of them. Using the impose mode would have filled in said indentations, which would then have to be carved out again.

I worked around this by making a design for the left edge of the windows, and imposing it on all the windows, then clearing the design and making a new one for the bottom edge and imposing again, (which also took care of the bottom left corners), then clearing and doing the same for the right and top edges. Like I said, it's doable in the current version, my suggestion just makes things faster/easier, since you'd only need one design and wouldn't have to clear it for each unique shape. Plus, if I ever decide to change the wallpaper to a different color, this would be a _very_ useful feature to have.

As for being different from the original request, my suggestion is also capable of fulfilling the purpose of an equal trade bit wand, it just also has additional functionality that replace > same material does not have. That's why I commented here instead of opening up a new issue.

**Comment by AlgorithmX2** [comment]
Well I think the existing functionality simplifies the more common case of replacing a single material with a new one, "pallet swapping" in a sense.

If you could please submit your request as a new request, I think its a good idea as well, but since it uses a pattern it would require an extra step for my other use case.

--

You can now replace materials as of 12.8, closing this request.
