### ISSUE TITLE
All C&B blocks disappeared updating from 0.3.4 => 1.0.63

### ISSUE THREAD

**Issue by znepb** [ChiselsAndBits/Chisels-and-Bits#937]
Hello, I recently updated my server, and all the mods along with it. However, when I loaded the world on the server, I was getting kicked with badly compressed packets, so I tried it on my client. Minecraft chewed up ram and other performance, and a few crashes later due to memory exhaustion (even with 32GB 3200Mhz), all C&B blocks in my world had dissappeared. Obviously I kept backups, so I went back with 0.3.4 and all blocks were still there on the backup. I believe this may have to do with the upgrade (and may be related to #709), but my world has many C&B blocks and it'd be quite a nightmare to replace all of them. Is there anything I can do to resolve this? All help is appreciated!

* MC Version: 1.16.5
* C&B Version: 1.0.63
* Do You have Optifine: Tested with & without OptiFine, problem persists either way

**Comment by marchermans** [comment]
Yeah there is not much I can do here, if you have a very large amount of blocks the conversion takes a large amount of memory and there is not much I can do to fix it.

I basically need to painfully copy the chiseled block bit data bit for bit to fix a bug I introduced during porting in the 0.x versions.

And that just takes a lot of memory to do.
Besides updating any further then that version is not possible anyway due to Mojang breaking stuff, and you will need to restart for 1.18.x anyway. So sorry to say: I won't be spending much time on trying to improve this code, especially since 1.19 is around the corner.
